/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"strings"
)

type V1RunnerImagesAPI interface {

	/*
		CreateRunnerImage Create a new runner image.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiCreateRunnerImageRequest
	*/
	CreateRunnerImage(ctx context.Context) ApiCreateRunnerImageRequest

	// CreateRunnerImageExecute executes the request
	//  @return CommonsRunnerImage
	CreateRunnerImageExecute(r ApiCreateRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error)

	/*
		DeleteRunnerImage Delete runner image details for the id.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Runner Image ID
		@return ApiDeleteRunnerImageRequest
	*/
	DeleteRunnerImage(ctx context.Context, id string) ApiDeleteRunnerImageRequest

	// DeleteRunnerImageExecute executes the request
	//  @return CommonsRunnerImage
	DeleteRunnerImageExecute(r ApiDeleteRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error)

	/*
		GetRunnerImage Get runner image details for the id.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Runner Image ID
		@return ApiGetRunnerImageRequest
	*/
	GetRunnerImage(ctx context.Context, id string) ApiGetRunnerImageRequest

	// GetRunnerImageExecute executes the request
	//  @return CommonsRunnerImage
	GetRunnerImageExecute(r ApiGetRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error)

	/*
		ListRunnerImages List all runner images.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@return ApiListRunnerImagesRequest
	*/
	ListRunnerImages(ctx context.Context) ApiListRunnerImagesRequest

	// ListRunnerImagesExecute executes the request
	//  @return CommonsListRunnerImagesOutput
	ListRunnerImagesExecute(r ApiListRunnerImagesRequest) (*CommonsListRunnerImagesOutput, *http.Response, error)

	/*
		UpdateRunnerImage Update runner image details for the id.

		@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
		@param id Runner Image ID
		@return ApiUpdateRunnerImageRequest
	*/
	UpdateRunnerImage(ctx context.Context, id string) ApiUpdateRunnerImageRequest

	// UpdateRunnerImageExecute executes the request
	//  @return CommonsRunnerImage
	UpdateRunnerImageExecute(r ApiUpdateRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error)
}

// V1RunnerImagesAPIService V1RunnerImagesAPI service
type V1RunnerImagesAPIService service

type ApiCreateRunnerImageRequest struct {
	ctx        context.Context
	ApiService V1RunnerImagesAPI
	body       *CommonsCreateRunnerImageInput
}

// Runner Image
func (r ApiCreateRunnerImageRequest) Body(body CommonsCreateRunnerImageInput) ApiCreateRunnerImageRequest {
	r.body = &body
	return r
}

func (r ApiCreateRunnerImageRequest) Execute() (*CommonsRunnerImage, *http.Response, error) {
	return r.ApiService.CreateRunnerImageExecute(r)
}

/*
CreateRunnerImage Create a new runner image.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateRunnerImageRequest
*/
func (a *V1RunnerImagesAPIService) CreateRunnerImage(ctx context.Context) ApiCreateRunnerImageRequest {
	return ApiCreateRunnerImageRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CommonsRunnerImage
func (a *V1RunnerImagesAPIService) CreateRunnerImageExecute(r ApiCreateRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunnerImage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnerImagesAPIService.CreateRunnerImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runner-images"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiDeleteRunnerImageRequest struct {
	ctx        context.Context
	ApiService V1RunnerImagesAPI
	id         string
}

func (r ApiDeleteRunnerImageRequest) Execute() (*CommonsRunnerImage, *http.Response, error) {
	return r.ApiService.DeleteRunnerImageExecute(r)
}

/*
DeleteRunnerImage Delete runner image details for the id.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner Image ID
	@return ApiDeleteRunnerImageRequest
*/
func (a *V1RunnerImagesAPIService) DeleteRunnerImage(ctx context.Context, id string) ApiDeleteRunnerImageRequest {
	return ApiDeleteRunnerImageRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunnerImage
func (a *V1RunnerImagesAPIService) DeleteRunnerImageExecute(r ApiDeleteRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunnerImage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnerImagesAPIService.DeleteRunnerImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runner-images/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetRunnerImageRequest struct {
	ctx        context.Context
	ApiService V1RunnerImagesAPI
	id         string
}

func (r ApiGetRunnerImageRequest) Execute() (*CommonsRunnerImage, *http.Response, error) {
	return r.ApiService.GetRunnerImageExecute(r)
}

/*
GetRunnerImage Get runner image details for the id.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner Image ID
	@return ApiGetRunnerImageRequest
*/
func (a *V1RunnerImagesAPIService) GetRunnerImage(ctx context.Context, id string) ApiGetRunnerImageRequest {
	return ApiGetRunnerImageRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunnerImage
func (a *V1RunnerImagesAPIService) GetRunnerImageExecute(r ApiGetRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunnerImage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnerImagesAPIService.GetRunnerImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runner-images/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListRunnerImagesRequest struct {
	ctx                                        context.Context
	ApiService                                 V1RunnerImagesAPI
	alias                                      *string
	runnerImagePullSecretId                    *string
	stackKind                                  *string
	region                                     *string
	arch                                       *[]string
	os                                         *[]string
	type_                                      *[]string
	warpbuildSnapshotImageVcsRepositoryNames   *[]string
	warpbuildSnapshotImageVcsRefNames          *[]string
	warpbuildSnapshotImageVcsOrganizationNames *[]string
	page                                       *int32
	perPage                                    *int32
}

// Alias
func (r ApiListRunnerImagesRequest) Alias(alias string) ApiListRunnerImagesRequest {
	r.alias = &alias
	return r
}

// Runner Image Pull Secret ID
func (r ApiListRunnerImagesRequest) RunnerImagePullSecretId(runnerImagePullSecretId string) ApiListRunnerImagesRequest {
	r.runnerImagePullSecretId = &runnerImagePullSecretId
	return r
}

// Stack Kind
func (r ApiListRunnerImagesRequest) StackKind(stackKind string) ApiListRunnerImagesRequest {
	r.stackKind = &stackKind
	return r
}

// Region
func (r ApiListRunnerImagesRequest) Region(region string) ApiListRunnerImagesRequest {
	r.region = &region
	return r
}

// Arch
func (r ApiListRunnerImagesRequest) Arch(arch []string) ApiListRunnerImagesRequest {
	r.arch = &arch
	return r
}

// OS
func (r ApiListRunnerImagesRequest) Os(os []string) ApiListRunnerImagesRequest {
	r.os = &os
	return r
}

// Type
func (r ApiListRunnerImagesRequest) Type_(type_ []string) ApiListRunnerImagesRequest {
	r.type_ = &type_
	return r
}

// Snapshot VCS Repositories Names. These will be an and operation so other image types if passed will be ignored except the warpbuild_managed images
func (r ApiListRunnerImagesRequest) WarpbuildSnapshotImageVcsRepositoryNames(warpbuildSnapshotImageVcsRepositoryNames []string) ApiListRunnerImagesRequest {
	r.warpbuildSnapshotImageVcsRepositoryNames = &warpbuildSnapshotImageVcsRepositoryNames
	return r
}

// Snapshot VCS Branches Names. These will be an and operation so other image types if passed will be ignored except the warpbuild_managed images
func (r ApiListRunnerImagesRequest) WarpbuildSnapshotImageVcsRefNames(warpbuildSnapshotImageVcsRefNames []string) ApiListRunnerImagesRequest {
	r.warpbuildSnapshotImageVcsRefNames = &warpbuildSnapshotImageVcsRefNames
	return r
}

// Snapshot VCS organization (GitHub org) names to filter snapshot images by
func (r ApiListRunnerImagesRequest) WarpbuildSnapshotImageVcsOrganizationNames(warpbuildSnapshotImageVcsOrganizationNames []string) ApiListRunnerImagesRequest {
	r.warpbuildSnapshotImageVcsOrganizationNames = &warpbuildSnapshotImageVcsOrganizationNames
	return r
}

// Page. Only supported when type doesn&#39;t include warpbuild_managed
func (r ApiListRunnerImagesRequest) Page(page int32) ApiListRunnerImagesRequest {
	r.page = &page
	return r
}

// Per Page. Only supported when type doesn&#39;t include warpbuild_managed
func (r ApiListRunnerImagesRequest) PerPage(perPage int32) ApiListRunnerImagesRequest {
	r.perPage = &perPage
	return r
}

func (r ApiListRunnerImagesRequest) Execute() (*CommonsListRunnerImagesOutput, *http.Response, error) {
	return r.ApiService.ListRunnerImagesExecute(r)
}

/*
ListRunnerImages List all runner images.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListRunnerImagesRequest
*/
func (a *V1RunnerImagesAPIService) ListRunnerImages(ctx context.Context) ApiListRunnerImagesRequest {
	return ApiListRunnerImagesRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CommonsListRunnerImagesOutput
func (a *V1RunnerImagesAPIService) ListRunnerImagesExecute(r ApiListRunnerImagesRequest) (*CommonsListRunnerImagesOutput, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsListRunnerImagesOutput
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnerImagesAPIService.ListRunnerImages")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runner-images"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.alias != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "alias", r.alias, "")
	}
	if r.runnerImagePullSecretId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "runner_image_pull_secret_id", r.runnerImagePullSecretId, "")
	}
	if r.stackKind != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "stack_kind", r.stackKind, "")
	}
	if r.region != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "region", r.region, "")
	}
	if r.arch != nil {
		t := *r.arch
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "arch", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "arch", t, "multi")
		}
	}
	if r.os != nil {
		t := *r.os
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "os", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "os", t, "multi")
		}
	}
	if r.type_ != nil {
		t := *r.type_
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "type", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "type", t, "multi")
		}
	}
	if r.warpbuildSnapshotImageVcsRepositoryNames != nil {
		t := *r.warpbuildSnapshotImageVcsRepositoryNames
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_repository_names", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_repository_names", t, "multi")
		}
	}
	if r.warpbuildSnapshotImageVcsRefNames != nil {
		t := *r.warpbuildSnapshotImageVcsRefNames
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_ref_names", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_ref_names", t, "multi")
		}
	}
	if r.warpbuildSnapshotImageVcsOrganizationNames != nil {
		t := *r.warpbuildSnapshotImageVcsOrganizationNames
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_organization_names", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "warpbuild_snapshot_image.vcs_organization_names", t, "multi")
		}
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "")
	}
	if r.perPage != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "per_page", r.perPage, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateRunnerImageRequest struct {
	ctx        context.Context
	ApiService V1RunnerImagesAPI
	id         string
	body       *CommonsUpdateRunnerImageInput
}

// Runner Image
func (r ApiUpdateRunnerImageRequest) Body(body CommonsUpdateRunnerImageInput) ApiUpdateRunnerImageRequest {
	r.body = &body
	return r
}

func (r ApiUpdateRunnerImageRequest) Execute() (*CommonsRunnerImage, *http.Response, error) {
	return r.ApiService.UpdateRunnerImageExecute(r)
}

/*
UpdateRunnerImage Update runner image details for the id.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner Image ID
	@return ApiUpdateRunnerImageRequest
*/
func (a *V1RunnerImagesAPIService) UpdateRunnerImage(ctx context.Context, id string) ApiUpdateRunnerImageRequest {
	return ApiUpdateRunnerImageRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunnerImage
func (a *V1RunnerImagesAPIService) UpdateRunnerImageExecute(r ApiUpdateRunnerImageRequest) (*CommonsRunnerImage, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPut
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunnerImage
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnerImagesAPIService.UpdateRunnerImage")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runner-images/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
