/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
)

type V1StacksAPI interface {

	/*
			ListStacks List stacks

			Lists all infrastructure stacks for the authenticated organization. Stacks represent the cloud infrastructure configurations where runners will be deployed.

		Stacks can be filtered by cloud provider type (ec2, gce, avm) and status.

		## Code Examples

		### Shell (curl)

		```bash
		# List all stacks
		curl -X GET "https://api.warpbuild.com/api/v1/stacks" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"

		# List only GCE stacks
		curl -X GET "https://api.warpbuild.com/api/v1/stacks?kind=gce" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"
		```

		### Example Response

		```json
		[
		  {
		    "id": "wbrakppu6twgj8el",
		    "created_at": "2024-11-12T14:04:23.653724Z",
		    "alias": "play-0001",
		    "kind": "gce",
		    "region": "us-central1",
		    "configurations": {
		      "gce_configurations": {
		        "vpc_id": "play-0001wbrakppu-vpc",
		        "storage_service_account_email": "sa-wbrakppu@playground-351903.iam.gserviceaccount.com",
		        "security_group": [
		          "play-0001-allow-internal"
		        ],
		        "subnets": [
		          {
		            "id": "play-0001wbrakppu-pu",
		            "az": "",
		            "is_public": true
		          },
		          {
		            "id": "play-0001wbrakppu-pr",
		            "az": "",
		            "is_public": false
		          }
		        ],
		        "cache_bucket": "play-0001-storage-bucket",
		        "observability_bucket": "play-0001-storage-bucket",
		        "tmpl_params": null
		      },
		      "default_tags": null
		    },
		    "connection_id": "f4a1e301-8adc-4142-8e0b-b4c8071ac266",
		    "organization_id": "wfmn080eif8rniwq",
		    "version": "v1.1",
		    "status": "active",
		    "onboarding_mode": "create",
		    "meta": {
		      "ec2_configurations": {
		        "aws_cloudformation_stack_id": ""
		      },
		      "is_preferred": false
		    },
		    "latest_version": ""
		  },
		  {
		    "id": "w1ltxzgxpv6o9bvp",
		    "created_at": "2025-10-08T10:46:37.844131Z",
		    "alias": "atk0",
		    "kind": "avm",
		    "region": "eastus",
		    "configurations": {
		      "default_tags": null
		    },
		    "connection_id": "9f77aea2-3162-44b4-b6f0-cdf84ce30a05",
		    "organization_id": "wfmn080eif8rniwq",
		    "version": "",
		    "status": "pending",
		    "onboarding_mode": "create",
		    "meta": {
		      "ec2_configurations": {
		        "aws_cloudformation_stack_id": ""
		      },
		      "is_preferred": false
		    },
		    "latest_version": "v1.0"
		  }
		]
		```

		### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/stacks',
		  {
		    method: 'GET',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    }
		  }
		);
		const stacks = await response.json();
		console.log(`Found ${stacks.length} stacks`);

		// Group by cloud provider
		const byKind = stacks.reduce((acc, stack) => {
		  acc[stack.kind] = (acc[stack.kind] || 0) + 1;
		  return acc;
		}, {});
		console.log('Stacks by provider:', byKind);
		```

		### Python

		```python
		import requests
		from collections import Counter

		response = requests.get(
		    'https://api.warpbuild.com/api/v1/stacks',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    }
		)
		stacks = response.json()
		print(f"Found {len(stacks)} stacks")

		# Group by cloud provider
		by_kind = Counter(stack['kind'] for stack in stacks)
		print(f"Stacks by provider: {dict(by_kind)}")

		# List active stacks
		active_stacks = [s for s in stacks if s['status'] == 'active']
		print(f"Active stacks: {len(active_stacks)}")
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@return ApiListStacksRequest
	*/
	ListStacks(ctx context.Context) ApiListStacksRequest

	// ListStacksExecute executes the request
	//  @return []CommonsStack
	ListStacksExecute(r ApiListStacksRequest) ([]CommonsStack, *http.Response, error)
}

// V1StacksAPIService V1StacksAPI service
type V1StacksAPIService service

type ApiListStacksRequest struct {
	ctx          context.Context
	ApiService   V1StacksAPI
	ids          *[]string
	kind         *string
	alias        *string
	region       *string
	connectionId *string
	status       *string
}

// list of stack id&#39;s
func (r ApiListStacksRequest) Ids(ids []string) ApiListStacksRequest {
	r.ids = &ids
	return r
}

// kind
func (r ApiListStacksRequest) Kind(kind string) ApiListStacksRequest {
	r.kind = &kind
	return r
}

// alias
func (r ApiListStacksRequest) Alias(alias string) ApiListStacksRequest {
	r.alias = &alias
	return r
}

// region
func (r ApiListStacksRequest) Region(region string) ApiListStacksRequest {
	r.region = &region
	return r
}

// connection_id
func (r ApiListStacksRequest) ConnectionId(connectionId string) ApiListStacksRequest {
	r.connectionId = &connectionId
	return r
}

// stack status
func (r ApiListStacksRequest) Status(status string) ApiListStacksRequest {
	r.status = &status
	return r
}

func (r ApiListStacksRequest) Execute() ([]CommonsStack, *http.Response, error) {
	return r.ApiService.ListStacksExecute(r)
}

/*
ListStacks List stacks

Lists all infrastructure stacks for the authenticated organization. Stacks represent the cloud infrastructure configurations where runners will be deployed.

Stacks can be filtered by cloud provider type (ec2, gce, avm) and status.

## Code Examples

### Shell (curl)

```bash
# List all stacks

	curl -X GET "https://api.warpbuild.com/api/v1/stacks" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

# List only GCE stacks

	curl -X GET "https://api.warpbuild.com/api/v1/stacks?kind=gce" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

```

### Example Response

```json
[

	{
	  "id": "wbrakppu6twgj8el",
	  "created_at": "2024-11-12T14:04:23.653724Z",
	  "alias": "play-0001",
	  "kind": "gce",
	  "region": "us-central1",
	  "configurations": {
	    "gce_configurations": {
	      "vpc_id": "play-0001wbrakppu-vpc",
	      "storage_service_account_email": "sa-wbrakppu@playground-351903.iam.gserviceaccount.com",
	      "security_group": [
	        "play-0001-allow-internal"
	      ],
	      "subnets": [
	        {
	          "id": "play-0001wbrakppu-pu",
	          "az": "",
	          "is_public": true
	        },
	        {
	          "id": "play-0001wbrakppu-pr",
	          "az": "",
	          "is_public": false
	        }
	      ],
	      "cache_bucket": "play-0001-storage-bucket",
	      "observability_bucket": "play-0001-storage-bucket",
	      "tmpl_params": null
	    },
	    "default_tags": null
	  },
	  "connection_id": "f4a1e301-8adc-4142-8e0b-b4c8071ac266",
	  "organization_id": "wfmn080eif8rniwq",
	  "version": "v1.1",
	  "status": "active",
	  "onboarding_mode": "create",
	  "meta": {
	    "ec2_configurations": {
	      "aws_cloudformation_stack_id": ""
	    },
	    "is_preferred": false
	  },
	  "latest_version": ""
	},
	{
	  "id": "w1ltxzgxpv6o9bvp",
	  "created_at": "2025-10-08T10:46:37.844131Z",
	  "alias": "atk0",
	  "kind": "avm",
	  "region": "eastus",
	  "configurations": {
	    "default_tags": null
	  },
	  "connection_id": "9f77aea2-3162-44b4-b6f0-cdf84ce30a05",
	  "organization_id": "wfmn080eif8rniwq",
	  "version": "",
	  "status": "pending",
	  "onboarding_mode": "create",
	  "meta": {
	    "ec2_configurations": {
	      "aws_cloudformation_stack_id": ""
	    },
	    "is_preferred": false
	  },
	  "latest_version": "v1.0"
	}

]
```

### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/stacks',
	{
	  method: 'GET',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  }
	}

);
const stacks = await response.json();
console.log(`Found ${stacks.length} stacks`);

// Group by cloud provider

	const byKind = stacks.reduce((acc, stack) => {
	  acc[stack.kind] = (acc[stack.kind] || 0) + 1;
	  return acc;
	}, {});

console.log('Stacks by provider:', byKind);
```

### Python

```python
import requests
from collections import Counter

response = requests.get(

	'https://api.warpbuild.com/api/v1/stacks',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	}

)
stacks = response.json()
print(f"Found {len(stacks)} stacks")

# Group by cloud provider
by_kind = Counter(stack['kind'] for stack in stacks)
print(f"Stacks by provider: {dict(by_kind)}")

# List active stacks
active_stacks = [s for s in stacks if s['status'] == 'active']
print(f"Active stacks: {len(active_stacks)}")
```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListStacksRequest
*/
func (a *V1StacksAPIService) ListStacks(ctx context.Context) ApiListStacksRequest {
	return ApiListStacksRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []CommonsStack
func (a *V1StacksAPIService) ListStacksExecute(r ApiListStacksRequest) ([]CommonsStack, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []CommonsStack
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1StacksAPIService.ListStacks")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/stacks"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.ids != nil {
		t := *r.ids
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "ids", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "ids", t, "multi")
		}
	}
	if r.kind != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "kind", r.kind, "")
	}
	if r.alias != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "alias", r.alias, "")
	}
	if r.region != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "region", r.region, "")
	}
	if r.connectionId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "connection_id", r.connectionId, "")
	}
	if r.status != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", r.status, "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		var v WarpBuildAPIError
		err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			newErr.error = err.Error()
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
		newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
