/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"strings"
)

type V1RunnersAPI interface {

	/*
			DeleteRunner Delete a runner

			Deletes a runner set from the authenticated organization. This will remove the runner configuration and prevent new instances from being provisioned.

		**Warning:** Any running instances associated with this runner will be terminated. This action cannot be undone.

		## Code Examples

		### Shell (curl)

		```bash
		curl -X DELETE "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"
		```

		### Example Response

		Returns an empty response with status code `200` on success.

		```json
		{}
		```

		### TypeScript

		```typescript
		const runnerId = 'wzvojxk17eo3s1dq';

		const response = await fetch(
		  `https://api.warpbuild.com/api/v1/runners/${runnerId}`,
		  {
		    method: 'DELETE',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    }
		  }
		);

		if (response.ok) {
		  console.log(`Runner ${runnerId} deleted successfully`);
		} else {
		  const error = await response.json();
		  console.error(`Failed to delete runner: ${error.message}`);
		}
		```

		### Python

		```python
		import requests

		runner_id = 'wzvojxk17eo3s1dq'

		response = requests.delete(
		    f'https://api.warpbuild.com/api/v1/runners/{runner_id}',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    }
		)

		if response.status_code == 200:
		    print(f"Runner {runner_id} deleted successfully")
		else:
		    print(f"Failed to delete runner: {response.json().get('message')}")
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param id Runner ID
			@return ApiDeleteRunnerRequest
	*/
	DeleteRunner(ctx context.Context, id string) ApiDeleteRunnerRequest

	// DeleteRunnerExecute executes the request
	//  @return CommonsRunner
	DeleteRunnerExecute(r ApiDeleteRunnerRequest) (*CommonsRunner, *http.Response, error)

	/*
			GetRunner Get runner details

			Retrieves a specific runner (runner set) by ID. Returns the runner configuration, status, labels, and associated metadata for the authenticated organization.

		A runner set defines the configuration template for runner instances that will be provisioned when CI/CD jobs request matching labels.

		## Code Examples

		### Shell (curl)

		```bash
		curl -X GET "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"
		```

		### Example Response

		```json
		{
		  "id": "wzvojxk17eo3s1dq",
		  "created_at": "2024-10-09T17:28:02.050974Z",
		  "updated_at": "2024-10-09T17:28:02.050974Z",
		  "name": "warpdev-custom-test-custom-image",
		  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		  "configuration": {
		    "sku": "4x-x64-w1kkdpjem73cmowh",
		    "storage": {
		      "tier": "low",
		      "size": 150,
		      "iops": 3200,
		      "throughput": 250,
		      "disk_type": "pd-balanced",
		      "performance_tier": ""
		    },
		    "image": "wjqcx6ozzghczk5x",
		    "capacity_type": "ondemand"
		  },
		  "stock_runner_id": null,
		  "organization_id": "wfmn080eif8rniwq",
		  "labels": [
		    "warpdev-custom-test-custom-image"
		  ],
		  "active": true,
		  "provider_id": "",
		  "meta": {}
		}
		```

		### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		  {
		    method: 'GET',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    }
		  }
		);
		const runner = await response.json();
		console.log(runner.name); // "warpdev-custom-test-custom-image"
		console.log(runner.configuration.sku); // "4x-x64-w1kkdpjem73cmowh"
		```

		### Python

		```python
		import requests

		response = requests.get(
		    'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    }
		)
		runner = response.json()
		print(runner['name'])  # "warpdev-custom-test-custom-image"
		print(runner['configuration']['sku'])  # "4x-x64-w1kkdpjem73cmowh"
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param id Runner ID
			@return ApiGetRunnerRequest
	*/
	GetRunner(ctx context.Context, id string) ApiGetRunnerRequest

	// GetRunnerExecute executes the request
	//  @return CommonsRunner
	GetRunnerExecute(r ApiGetRunnerRequest) (*CommonsRunner, *http.Response, error)

	/*
			ListRunners List runners

			Lists all runner sets for the authenticated organization. Runner sets define the configuration templates for runner instances that will be provisioned when CI/CD jobs request matching labels.

		You can filter the results by image, provider, VCS integration, and other criteria using query parameters.

		## Code Examples

		### Shell (curl)

		```bash
		# List all runners
		curl -X GET "https://api.warpbuild.com/api/v1/runners" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"

		# List runners with filters
		curl -X GET "https://api.warpbuild.com/api/v1/runners?image=ubuntu-2204&active=true" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json"
		```

		### Example Response

		```json
		[
		  {
		    "id": "wzvojxk17eo3s1dq",
		    "created_at": "2024-10-09T17:28:02.050974Z",
		    "updated_at": "2024-10-09T17:28:02.050974Z",
		    "name": "warpdev-custom-test-custom-image",
		    "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		    "configuration": {
		      "sku": "4x-x64-w1kkdpjem73cmowh",
		      "storage": {
		        "tier": "low",
		        "size": 150,
		        "iops": 3200,
		        "throughput": 250,
		        "disk_type": "pd-balanced",
		        "performance_tier": ""
		      },
		      "image": "wjqcx6ozzghczk5x",
		      "capacity_type": "ondemand"
		    },
		    "stock_runner_id": null,
		    "organization_id": "wfmn080eif8rniwq",
		    "labels": [
		      "warpdev-custom-test-custom-image"
		    ],
		    "active": true,
		    "provider_id": "",
		    "meta": {}
		  },
		  {
		    "id": "ws61znyfcp3mh95j",
		    "created_at": "2024-10-25T06:32:50.900502Z",
		    "updated_at": "2024-10-25T06:32:50.900502Z",
		    "name": "warpdev-ubuntu-2204-x64-8x",
		    "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		    "configuration": {
		      "sku": "8x-x64-w80f032rccrc9nh2",
		      "storage": {
		        "tier": "custom",
		        "size": 256,
		        "iops": 6666,
		        "throughput": 444,
		        "disk_type": "",
		        "performance_tier": "P30"
		      },
		      "image": "ubuntu-2204",
		      "capacity_type": "ondemand"
		    },
		    "stock_runner_id": "stock-8x-x64-w80f032rccrc9nh2-VGcq1lK9Oa",
		    "organization_id": "wfmn080eif8rniwq",
		    "labels": [
		      "warpdev-ubuntu-2204-x64-8x"
		    ],
		    "active": true,
		    "provider_id": null,
		    "meta": {}
		  }
		]
		```

		### TypeScript

		```typescript
		// List all runners
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners',
		  {
		    method: 'GET',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    }
		  }
		);
		const runners = await response.json();
		console.log(`Found ${runners.length} runners`);

		// List runners with filters
		const params = new URLSearchParams({
		  image: 'ubuntu-2204',
		  active: 'true'
		});
		const filteredResponse = await fetch(
		  `https://api.warpbuild.com/api/v1/runners?${params}`,
		  {
		    method: 'GET',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    }
		  }
		);
		const filteredRunners = await filteredResponse.json();
		```

		### Python

		```python
		import requests

		# List all runners
		response = requests.get(
		    'https://api.warpbuild.com/api/v1/runners',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    }
		)
		runners = response.json()
		print(f"Found {len(runners)} runners")

		# List runners with filters
		filtered_response = requests.get(
		    'https://api.warpbuild.com/api/v1/runners',
		    params={
		        'image': 'ubuntu-2204',
		        'active': True
		    },
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    }
		)
		filtered_runners = filtered_response.json()
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@return ApiListRunnersRequest
	*/
	ListRunners(ctx context.Context) ApiListRunnersRequest

	// ListRunnersExecute executes the request
	//  @return []CommonsRunner
	ListRunnersExecute(r ApiListRunnersRequest) ([]CommonsRunner, *http.Response, error)

	/*
			SetupRunner Create a new runner

			Creates a new runner set for the authenticated organization. A runner set defines the configuration template for runner instances that will be provisioned when CI/CD jobs request matching labels.

		You can create different types of runners:
		- **Stock runners**: WarpBuild managed runners with pre-configured images
		- **Custom runners**: Bring Your Own Cloud (BYOC) runners on AWS EC2, GCP, or Azure
		- **Custom image runners**: Runners with custom container images or custom AMIs

		## Code Examples

		### 1. Create a Stock Runner (WarpBuild Managed)

		Stock runners use WarpBuild's managed infrastructure with pre-configured images.

		#### Shell (curl)

		```bash
		curl -X POST "https://api.warpbuild.com/api/v1/runners" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "name": "my-ubuntu-runner-8x",
		       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		       "labels": ["my-ubuntu-runner-8x"],
		       "configuration": {
		         "sku": "8x-x64-w80f032rccrc9nh2",
		         "image": "ubuntu-2204",
		         "capacity_type": "ondemand",
		         "storage": {
		           "tier": "medium",
		           "size": 150
		         }
		       }
		     }'
		```

		#### Example Response

		```json
		{
		  "id": "wnewrunner12345",
		  "created_at": "2024-12-25T10:00:00.000000Z",
		  "updated_at": "2024-12-25T10:00:00.000000Z",
		  "name": "my-ubuntu-runner-8x",
		  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		  "configuration": {
		    "sku": "8x-x64-w80f032rccrc9nh2",
		    "storage": {
		      "tier": "medium",
		      "size": 150,
		      "iops": 3000,
		      "throughput": 125,
		      "disk_type": "",
		      "performance_tier": ""
		    },
		    "image": "ubuntu-2204",
		    "capacity_type": "ondemand"
		  },
		  "stock_runner_id": "stock-8x-x64-w80f032rccrc9nh2-ABC123",
		  "organization_id": "wfmn080eif8rniwq",
		  "labels": ["my-ubuntu-runner-8x"],
		  "active": true,
		  "provider_id": null,
		  "meta": {}
		}
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners',
		  {
		    method: 'POST',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      name: 'my-ubuntu-runner-8x',
		      vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
		      labels: ['my-ubuntu-runner-8x'],
		      configuration: {
		        sku: '8x-x64-w80f032rccrc9nh2',
		        image: 'ubuntu-2204',
		        capacity_type: 'ondemand',
		        storage: {
		          tier: 'medium',
		          size: 150
		        }
		      }
		    })
		  }
		);
		const runner = await response.json();
		console.log(`Created runner: ${runner.id}`);
		```

		#### Python

		```python
		import requests

		response = requests.post(
		    'https://api.warpbuild.com/api/v1/runners',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'name': 'my-ubuntu-runner-8x',
		        'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
		        'labels': ['my-ubuntu-runner-8x'],
		        'configuration': {
		            'sku': '8x-x64-w80f032rccrc9nh2',
		            'image': 'ubuntu-2204',
		            'capacity_type': 'ondemand',
		            'storage': {
		                'tier': 'medium',
		                'size': 150
		            }
		        }
		    }
		)
		runner = response.json()
		print(f"Created runner: {runner['id']}")
		```

		### 2. Create a Custom Runner on GCP (BYOC)

		Bring Your Own Cloud runner on Google Cloud Platform using your GCP project.

		#### Shell (curl)

		```bash
		curl -X POST "https://api.warpbuild.com/api/v1/runners" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "name": "my-gcp-runner",
		       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		       "provider_id": "ee7c619a-c68d-47e5-8385-1aac164cb555",
		       "labels": ["self-hosted", "linux", "x64", "gcp"],
		       "configuration": {
		         "image": "ubuntu-2404",
		         "capacity_type": "spot",
		         "byoc_sku": {
		           "arch": "x64",
		           "is_public": false,
		           "instance_types": ["n2-standard-4", "n2-standard-8"],
		           "network_tier": "STANDARD"
		         },
		         "storage": {
		           "tier": "custom",
		           "size": 200,
		           "disk_type": "pd-ssd"
		         }
		       }
		     }'
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners',
		  {
		    method: 'POST',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      name: 'my-gcp-runner',
		      vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
		      provider_id: 'ee7c619a-c68d-47e5-8385-1aac164cb555',
		      labels: ['self-hosted', 'linux', 'x64', 'gcp'],
		      configuration: {
		        image: 'ubuntu-2404',
		        capacity_type: 'spot',
		        byoc_sku: {
		          arch: 'x64',
		          is_public: false,
		          instance_types: ['n2-standard-4', 'n2-standard-8'],
		          network_tier: 'STANDARD'
		        },
		        storage: {
		          tier: 'custom',
		          size: 200,
		          disk_type: 'pd-ssd'
		        }
		      }
		    })
		  }
		);
		const runner = await response.json();
		```

		#### Python

		```python
		import requests

		response = requests.post(
		    'https://api.warpbuild.com/api/v1/runners',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'name': 'my-gcp-runner',
		        'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
		        'provider_id': 'ee7c619a-c68d-47e5-8385-1aac164cb555',
		        'labels': ['self-hosted', 'linux', 'x64', 'gcp'],
		        'configuration': {
		            'image': 'ubuntu-2404',
		            'capacity_type': 'spot',
		            'byoc_sku': {
		                'arch': 'x64',
		                'is_public': False,
		                'instance_types': ['n2-standard-4', 'n2-standard-8'],
		                'network_tier': 'STANDARD'
		            },
		            'storage': {
		                'tier': 'custom',
		                'size': 200,
		                'disk_type': 'pd-ssd'
		            }
		        }
		    }
		)
		runner = response.json()
		```

		### 3. Create a Custom Runner on Azure (BYOC)

		Bring Your Own Cloud runner on Microsoft Azure.

		#### Shell (curl)

		```bash
		curl -X POST "https://api.warpbuild.com/api/v1/runners" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "name": "my-azure-runner",
		       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		       "provider_id": "9f77aea2-3162-44b4-b6f0-cdf84ce30a05",
		       "labels": ["self-hosted", "linux", "x64", "azure"],
		       "configuration": {
		         "image": "ubuntu-2404",
		         "capacity_type": "spot",
		         "byoc_sku": {
		           "arch": "x64",
		           "is_public": false,
		           "instance_types": ["Standard_D4s_v3", "Standard_D8s_v3"]
		         },
		         "storage": {
		           "tier": "high",
		           "size": 200,
		           "performance_tier": "P30"
		         }
		       }
		     }'
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners',
		  {
		    method: 'POST',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      name: 'my-azure-runner',
		      vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
		      provider_id: '9f77aea2-3162-44b4-b6f0-cdf84ce30a05',
		      labels: ['self-hosted', 'linux', 'x64', 'azure'],
		      configuration: {
		        image: 'ubuntu-2404',
		        capacity_type: 'spot',
		        byoc_sku: {
		          arch: 'x64',
		          is_public: false,
		          instance_types: ['Standard_D4s_v3', 'Standard_D8s_v3']
		        },
		        storage: {
		          tier: 'high',
		          size: 200,
		          performance_tier: 'P30'
		        }
		      }
		    })
		  }
		);
		const runner = await response.json();
		```

		#### Python

		```python
		import requests

		response = requests.post(
		    'https://api.warpbuild.com/api/v1/runners',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'name': 'my-azure-runner',
		        'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
		        'provider_id': '9f77aea2-3162-44b4-b6f0-cdf84ce30a05',
		        'labels': ['self-hosted', 'linux', 'x64', 'azure'],
		        'configuration': {
		            'image': 'ubuntu-2404',
		            'capacity_type': 'spot',
		            'byoc_sku': {
		                'arch': 'x64',
		                'is_public': False,
		                'instance_types': ['Standard_D4s_v3', 'Standard_D8s_v3']
		            },
		            'storage': {
		                'tier': 'high',
		                'size': 200,
		                'performance_tier': 'P30'
		            }
		        }
		    }
		)
		runner = response.json()
		```

		### 4. Create a Custom Runner with Custom Image

		Runner using a custom container image with a specific SKU.

		#### Shell (curl)

		```bash
		curl -X POST "https://api.warpbuild.com/api/v1/runners" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "name": "warpdev-custom-test-custom-image",
		       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		       "labels": ["warpdev-custom-test-custom-image"],
		       "configuration": {
		         "sku": "4x-x64-w1kkdpjem73cmowh",
		         "image": "wjqcx6ozzghczk5x",
		         "capacity_type": "ondemand",
		         "storage": {
		           "tier": "low",
		           "size": 150,
		           "iops": 3200,
		           "throughput": 250,
		           "disk_type": "pd-balanced"
		         }
		       }
		     }'
		```

		#### Example Response

		```json
		{
		  "id": "wzvojxk17eo3s1dq",
		  "created_at": "2024-10-09T17:28:02.050974Z",
		  "updated_at": "2024-10-09T17:28:02.050974Z",
		  "name": "warpdev-custom-test-custom-image",
		  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		  "configuration": {
		    "sku": "4x-x64-w1kkdpjem73cmowh",
		    "storage": {
		      "tier": "low",
		      "size": 150,
		      "iops": 3200,
		      "throughput": 250,
		      "disk_type": "pd-balanced",
		      "performance_tier": ""
		    },
		    "image": "wjqcx6ozzghczk5x",
		    "capacity_type": "ondemand"
		  },
		  "stock_runner_id": null,
		  "organization_id": "wfmn080eif8rniwq",
		  "labels": [
		    "warpdev-custom-test-custom-image"
		  ],
		  "active": true,
		  "provider_id": "",
		  "meta": {}
		}
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners',
		  {
		    method: 'POST',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      name: 'warpdev-custom-test-custom-image',
		      vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
		      labels: ['warpdev-custom-test-custom-image'],
		      configuration: {
		        sku: '4x-x64-w1kkdpjem73cmowh',
		        image: 'wjqcx6ozzghczk5x',
		        capacity_type: 'ondemand',
		        storage: {
		          tier: 'low',
		          size: 150,
		          iops: 3200,
		          throughput: 250,
		          disk_type: 'pd-balanced'
		        }
		      }
		    })
		  }
		);
		const runner = await response.json();
		```

		#### Python

		```python
		import requests

		response = requests.post(
		    'https://api.warpbuild.com/api/v1/runners',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'name': 'warpdev-custom-test-custom-image',
		        'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
		        'labels': ['warpdev-custom-test-custom-image'],
		        'configuration': {
		            'sku': '4x-x64-w1kkdpjem73cmowh',
		            'image': 'wjqcx6ozzghczk5x',
		            'capacity_type': 'ondemand',
		            'storage': {
		                'tier': 'low',
		                'size': 150,
		                'iops': 3200,
		                'throughput': 250,
		                'disk_type': 'pd-balanced'
		            }
		        }
		    }
		)
		runner = response.json()
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@return ApiSetupRunnerRequest
	*/
	SetupRunner(ctx context.Context) ApiSetupRunnerRequest

	// SetupRunnerExecute executes the request
	//  @return CommonsRunner
	SetupRunnerExecute(r ApiSetupRunnerRequest) (*CommonsRunner, *http.Response, error)

	/*
			UpdateRunner Update a runner

			Updates an existing runner set configuration. Only the fields specified in the request body will be updated; all other fields remain unchanged.

		You can update various aspects of a runner including its name, labels, storage configuration, and capacity type.

		## Code Examples

		### 1. Update Runner Labels

		#### Shell (curl)

		```bash
		curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "labels": ["my-runner", "ubuntu", "x64"]
		     }'
		```

		#### Example Response

		```json
		{
		  "id": "wzvojxk17eo3s1dq",
		  "created_at": "2024-10-09T17:28:02.050974Z",
		  "updated_at": "2024-12-25T10:30:00.000000Z",
		  "name": "warpdev-custom-test-custom-image",
		  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
		  "configuration": {
		    "sku": "4x-x64-w1kkdpjem73cmowh",
		    "storage": {
		      "tier": "low",
		      "size": 150,
		      "iops": 3200,
		      "throughput": 250,
		      "disk_type": "pd-balanced",
		      "performance_tier": ""
		    },
		    "image": "wjqcx6ozzghczk5x",
		    "capacity_type": "ondemand"
		  },
		  "stock_runner_id": null,
		  "organization_id": "wfmn080eif8rniwq",
		  "labels": [
		    "my-runner",
		    "ubuntu",
		    "x64"
		  ],
		  "active": true,
		  "provider_id": "",
		  "meta": {}
		}
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		  {
		    method: 'PUT',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      labels: ['my-runner', 'ubuntu', 'x64']
		    })
		  }
		);
		const updatedRunner = await response.json();
		console.log(`Updated labels: ${updatedRunner.labels.join(', ')}`);
		```

		#### Python

		```python
		import requests

		response = requests.put(
		    'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'labels': ['my-runner', 'ubuntu', 'x64']
		    }
		)
		updated_runner = response.json()
		print(f"Updated labels: {updated_runner['labels']}")
		```

		### 2. Update Runner Configuration

		#### Shell (curl)

		```bash
		curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "configuration": {
		         "sku": "8x-x64-w80f032rccrc9nh2",
		         "capacity_type": "spot",
		         "storage": {
		           "tier": "high",
		           "size": 200
		         }
		       }
		     }'
		```

		#### TypeScript

		```typescript
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		  {
		    method: 'PUT',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      configuration: {
		        sku: '8x-x64-w80f032rccrc9nh2',
		        capacity_type: 'spot',
		        storage: {
		          tier: 'high',
		          size: 200
		        }
		      }
		    })
		  }
		);
		const updatedRunner = await response.json();
		```

		#### Python

		```python
		import requests

		response = requests.put(
		    'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'configuration': {
		            'sku': '8x-x64-w80f032rccrc9nh2',
		            'capacity_type': 'spot',
		            'storage': {
		                'tier': 'high',
		                'size': 200
		            }
		        }
		    }
		)
		updated_runner = response.json()
		```

		### 3. Enable/Disable Runner

		#### Shell (curl)

		```bash
		# Disable a runner
		curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "active": false
		     }'

		# Re-enable a runner
		curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
		     -H "Authorization: Bearer <your-api-key>" \
		     -H "Content-Type: application/json" \
		     -d '{
		       "active": true
		     }'
		```

		#### TypeScript

		```typescript
		// Disable a runner
		const response = await fetch(
		  'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		  {
		    method: 'PUT',
		    headers: {
		      'Authorization': 'Bearer <your-api-key>',
		      'Content-Type': 'application/json'
		    },
		    body: JSON.stringify({
		      active: false
		    })
		  }
		);
		const updatedRunner = await response.json();
		console.log(`Runner active: ${updatedRunner.active}`);
		```

		#### Python

		```python
		import requests

		# Disable a runner
		response = requests.put(
		    'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
		    headers={
		        'Authorization': 'Bearer <your-api-key>',
		        'Content-Type': 'application/json'
		    },
		    json={
		        'active': False
		    }
		)
		updated_runner = response.json()
		print(f"Runner active: {updated_runner['active']}")
		```


			@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
			@param id Runner ID
			@return ApiUpdateRunnerRequest
	*/
	UpdateRunner(ctx context.Context, id string) ApiUpdateRunnerRequest

	// UpdateRunnerExecute executes the request
	//  @return CommonsRunner
	UpdateRunnerExecute(r ApiUpdateRunnerRequest) (*CommonsRunner, *http.Response, error)
}

// V1RunnersAPIService V1RunnersAPI service
type V1RunnersAPIService service

type ApiDeleteRunnerRequest struct {
	ctx        context.Context
	ApiService V1RunnersAPI
	id         string
}

func (r ApiDeleteRunnerRequest) Execute() (*CommonsRunner, *http.Response, error) {
	return r.ApiService.DeleteRunnerExecute(r)
}

/*
DeleteRunner Delete a runner

Deletes a runner set from the authenticated organization. This will remove the runner configuration and prevent new instances from being provisioned.

**Warning:** Any running instances associated with this runner will be terminated. This action cannot be undone.

## Code Examples

### Shell (curl)

```bash

	curl -X DELETE "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

```

### Example Response

Returns an empty response with status code `200` on success.

```json
{}
```

### TypeScript

```typescript
const runnerId = 'wzvojxk17eo3s1dq';

const response = await fetch(

	`https://api.warpbuild.com/api/v1/runners/${runnerId}`,
	{
	  method: 'DELETE',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  }
	}

);

	if (response.ok) {
	  console.log(`Runner ${runnerId} deleted successfully`);
	} else {

	  const error = await response.json();
	  console.error(`Failed to delete runner: ${error.message}`);
	}

```

### Python

```python
import requests

runner_id = 'wzvojxk17eo3s1dq'

response = requests.delete(

	f'https://api.warpbuild.com/api/v1/runners/{runner_id}',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	}

)

if response.status_code == 200:

	print(f"Runner {runner_id} deleted successfully")

else:

	print(f"Failed to delete runner: {response.json().get('message')}")

```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner ID
	@return ApiDeleteRunnerRequest
*/
func (a *V1RunnersAPIService) DeleteRunner(ctx context.Context, id string) ApiDeleteRunnerRequest {
	return ApiDeleteRunnerRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunner
func (a *V1RunnersAPIService) DeleteRunnerExecute(r ApiDeleteRunnerRequest) (*CommonsRunner, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodDelete
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnersAPIService.DeleteRunner")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetRunnerRequest struct {
	ctx        context.Context
	ApiService V1RunnersAPI
	id         string
}

func (r ApiGetRunnerRequest) Execute() (*CommonsRunner, *http.Response, error) {
	return r.ApiService.GetRunnerExecute(r)
}

/*
GetRunner Get runner details

Retrieves a specific runner (runner set) by ID. Returns the runner configuration, status, labels, and associated metadata for the authenticated organization.

A runner set defines the configuration template for runner instances that will be provisioned when CI/CD jobs request matching labels.

## Code Examples

### Shell (curl)

```bash

	curl -X GET "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

```

### Example Response

```json

	{
	  "id": "wzvojxk17eo3s1dq",
	  "created_at": "2024-10-09T17:28:02.050974Z",
	  "updated_at": "2024-10-09T17:28:02.050974Z",
	  "name": "warpdev-custom-test-custom-image",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "4x-x64-w1kkdpjem73cmowh",
	    "storage": {
	      "tier": "low",
	      "size": 150,
	      "iops": 3200,
	      "throughput": 250,
	      "disk_type": "pd-balanced",
	      "performance_tier": ""
	    },
	    "image": "wjqcx6ozzghczk5x",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": null,
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": [
	    "warpdev-custom-test-custom-image"
	  ],
	  "active": true,
	  "provider_id": "",
	  "meta": {}
	}

```

### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	{
	  method: 'GET',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  }
	}

);
const runner = await response.json();
console.log(runner.name); // "warpdev-custom-test-custom-image"
console.log(runner.configuration.sku); // "4x-x64-w1kkdpjem73cmowh"
```

### Python

```python
import requests

response = requests.get(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	}

)
runner = response.json()
print(runner['name'])  # "warpdev-custom-test-custom-image"
print(runner['configuration']['sku'])  # "4x-x64-w1kkdpjem73cmowh"
```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner ID
	@return ApiGetRunnerRequest
*/
func (a *V1RunnersAPIService) GetRunner(ctx context.Context, id string) ApiGetRunnerRequest {
	return ApiGetRunnerRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunner
func (a *V1RunnersAPIService) GetRunnerExecute(r ApiGetRunnerRequest) (*CommonsRunner, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnersAPIService.GetRunner")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListRunnersRequest struct {
	ctx              context.Context
	ApiService       V1RunnersAPI
	image            *string
	ids              *[]string
	providerId       *string
	vcsIntegrationId *string
	active           *bool
	labels           *[]string
}

// Image
func (r ApiListRunnersRequest) Image(image string) ApiListRunnersRequest {
	r.image = &image
	return r
}

// list of runner set id&#39;s
func (r ApiListRunnersRequest) Ids(ids []string) ApiListRunnersRequest {
	r.ids = &ids
	return r
}

// provider kind id
func (r ApiListRunnersRequest) ProviderId(providerId string) ApiListRunnersRequest {
	r.providerId = &providerId
	return r
}

// Deprecated: ignored — runner sets are organization-global
func (r ApiListRunnersRequest) VcsIntegrationId(vcsIntegrationId string) ApiListRunnersRequest {
	r.vcsIntegrationId = &vcsIntegrationId
	return r
}

// active
func (r ApiListRunnersRequest) Active(active bool) ApiListRunnersRequest {
	r.active = &active
	return r
}

// labels
func (r ApiListRunnersRequest) Labels(labels []string) ApiListRunnersRequest {
	r.labels = &labels
	return r
}

func (r ApiListRunnersRequest) Execute() ([]CommonsRunner, *http.Response, error) {
	return r.ApiService.ListRunnersExecute(r)
}

/*
ListRunners List runners

Lists all runner sets for the authenticated organization. Runner sets define the configuration templates for runner instances that will be provisioned when CI/CD jobs request matching labels.

You can filter the results by image, provider, VCS integration, and other criteria using query parameters.

## Code Examples

### Shell (curl)

```bash
# List all runners

	curl -X GET "https://api.warpbuild.com/api/v1/runners" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

# List runners with filters

	curl -X GET "https://api.warpbuild.com/api/v1/runners?image=ubuntu-2204&active=true" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json"

```

### Example Response

```json
[

	{
	  "id": "wzvojxk17eo3s1dq",
	  "created_at": "2024-10-09T17:28:02.050974Z",
	  "updated_at": "2024-10-09T17:28:02.050974Z",
	  "name": "warpdev-custom-test-custom-image",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "4x-x64-w1kkdpjem73cmowh",
	    "storage": {
	      "tier": "low",
	      "size": 150,
	      "iops": 3200,
	      "throughput": 250,
	      "disk_type": "pd-balanced",
	      "performance_tier": ""
	    },
	    "image": "wjqcx6ozzghczk5x",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": null,
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": [
	    "warpdev-custom-test-custom-image"
	  ],
	  "active": true,
	  "provider_id": "",
	  "meta": {}
	},
	{
	  "id": "ws61znyfcp3mh95j",
	  "created_at": "2024-10-25T06:32:50.900502Z",
	  "updated_at": "2024-10-25T06:32:50.900502Z",
	  "name": "warpdev-ubuntu-2204-x64-8x",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "8x-x64-w80f032rccrc9nh2",
	    "storage": {
	      "tier": "custom",
	      "size": 256,
	      "iops": 6666,
	      "throughput": 444,
	      "disk_type": "",
	      "performance_tier": "P30"
	    },
	    "image": "ubuntu-2204",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": "stock-8x-x64-w80f032rccrc9nh2-VGcq1lK9Oa",
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": [
	    "warpdev-ubuntu-2204-x64-8x"
	  ],
	  "active": true,
	  "provider_id": null,
	  "meta": {}
	}

]
```

### TypeScript

```typescript
// List all runners
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners',
	{
	  method: 'GET',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  }
	}

);
const runners = await response.json();
console.log(`Found ${runners.length} runners`);

// List runners with filters

	const params = new URLSearchParams({
	  image: 'ubuntu-2204',
	  active: 'true'
	});

const filteredResponse = await fetch(

	`https://api.warpbuild.com/api/v1/runners?${params}`,
	{
	  method: 'GET',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  }
	}

);
const filteredRunners = await filteredResponse.json();
```

### Python

```python
import requests

# List all runners
response = requests.get(

	'https://api.warpbuild.com/api/v1/runners',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	}

)
runners = response.json()
print(f"Found {len(runners)} runners")

# List runners with filters
filtered_response = requests.get(

	'https://api.warpbuild.com/api/v1/runners',
	params={
	    'image': 'ubuntu-2204',
	    'active': True
	},
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	}

)
filtered_runners = filtered_response.json()
```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListRunnersRequest
*/
func (a *V1RunnersAPIService) ListRunners(ctx context.Context) ApiListRunnersRequest {
	return ApiListRunnersRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return []CommonsRunner
func (a *V1RunnersAPIService) ListRunnersExecute(r ApiListRunnersRequest) ([]CommonsRunner, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodGet
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue []CommonsRunner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnersAPIService.ListRunners")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.image != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "image", r.image, "")
	}
	if r.ids != nil {
		t := *r.ids
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "ids", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "ids", t, "multi")
		}
	}
	if r.providerId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "provider_id", r.providerId, "")
	}
	if r.vcsIntegrationId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "vcs_integration_id", r.vcsIntegrationId, "")
	}
	if r.active != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "active", r.active, "")
	}
	if r.labels != nil {
		t := *r.labels
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "labels", s.Index(i).Interface(), "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "labels", t, "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		var v WarpBuildAPIError
		err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			newErr.error = err.Error()
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
		newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSetupRunnerRequest struct {
	ctx        context.Context
	ApiService V1RunnersAPI
	body       *CommonsSetupRunnerInput
}

// Create new runner body
func (r ApiSetupRunnerRequest) Body(body CommonsSetupRunnerInput) ApiSetupRunnerRequest {
	r.body = &body
	return r
}

func (r ApiSetupRunnerRequest) Execute() (*CommonsRunner, *http.Response, error) {
	return r.ApiService.SetupRunnerExecute(r)
}

/*
SetupRunner Create a new runner

Creates a new runner set for the authenticated organization. A runner set defines the configuration template for runner instances that will be provisioned when CI/CD jobs request matching labels.

You can create different types of runners:
- **Stock runners**: WarpBuild managed runners with pre-configured images
- **Custom runners**: Bring Your Own Cloud (BYOC) runners on AWS EC2, GCP, or Azure
- **Custom image runners**: Runners with custom container images or custom AMIs

## Code Examples

### 1. Create a Stock Runner (WarpBuild Managed)

Stock runners use WarpBuild's managed infrastructure with pre-configured images.

#### Shell (curl)

```bash

	curl -X POST "https://api.warpbuild.com/api/v1/runners" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "name": "my-ubuntu-runner-8x",
	       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	       "labels": ["my-ubuntu-runner-8x"],
	       "configuration": {
	         "sku": "8x-x64-w80f032rccrc9nh2",
	         "image": "ubuntu-2204",
	         "capacity_type": "ondemand",
	         "storage": {
	           "tier": "medium",
	           "size": 150
	         }
	       }
	     }'

```

#### Example Response

```json

	{
	  "id": "wnewrunner12345",
	  "created_at": "2024-12-25T10:00:00.000000Z",
	  "updated_at": "2024-12-25T10:00:00.000000Z",
	  "name": "my-ubuntu-runner-8x",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "8x-x64-w80f032rccrc9nh2",
	    "storage": {
	      "tier": "medium",
	      "size": 150,
	      "iops": 3000,
	      "throughput": 125,
	      "disk_type": "",
	      "performance_tier": ""
	    },
	    "image": "ubuntu-2204",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": "stock-8x-x64-w80f032rccrc9nh2-ABC123",
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": ["my-ubuntu-runner-8x"],
	  "active": true,
	  "provider_id": null,
	  "meta": {}
	}

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners',
	{
	  method: 'POST',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    name: 'my-ubuntu-runner-8x',
	    vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
	    labels: ['my-ubuntu-runner-8x'],
	    configuration: {
	      sku: '8x-x64-w80f032rccrc9nh2',
	      image: 'ubuntu-2204',
	      capacity_type: 'ondemand',
	      storage: {
	        tier: 'medium',
	        size: 150
	      }
	    }
	  })
	}

);
const runner = await response.json();
console.log(`Created runner: ${runner.id}`);
```

#### Python

```python
import requests

response = requests.post(

	'https://api.warpbuild.com/api/v1/runners',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'name': 'my-ubuntu-runner-8x',
	    'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
	    'labels': ['my-ubuntu-runner-8x'],
	    'configuration': {
	        'sku': '8x-x64-w80f032rccrc9nh2',
	        'image': 'ubuntu-2204',
	        'capacity_type': 'ondemand',
	        'storage': {
	            'tier': 'medium',
	            'size': 150
	        }
	    }
	}

)
runner = response.json()
print(f"Created runner: {runner['id']}")
```

### 2. Create a Custom Runner on GCP (BYOC)

Bring Your Own Cloud runner on Google Cloud Platform using your GCP project.

#### Shell (curl)

```bash

	curl -X POST "https://api.warpbuild.com/api/v1/runners" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "name": "my-gcp-runner",
	       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	       "provider_id": "ee7c619a-c68d-47e5-8385-1aac164cb555",
	       "labels": ["self-hosted", "linux", "x64", "gcp"],
	       "configuration": {
	         "image": "ubuntu-2404",
	         "capacity_type": "spot",
	         "byoc_sku": {
	           "arch": "x64",
	           "is_public": false,
	           "instance_types": ["n2-standard-4", "n2-standard-8"],
	           "network_tier": "STANDARD"
	         },
	         "storage": {
	           "tier": "custom",
	           "size": 200,
	           "disk_type": "pd-ssd"
	         }
	       }
	     }'

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners',
	{
	  method: 'POST',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    name: 'my-gcp-runner',
	    vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
	    provider_id: 'ee7c619a-c68d-47e5-8385-1aac164cb555',
	    labels: ['self-hosted', 'linux', 'x64', 'gcp'],
	    configuration: {
	      image: 'ubuntu-2404',
	      capacity_type: 'spot',
	      byoc_sku: {
	        arch: 'x64',
	        is_public: false,
	        instance_types: ['n2-standard-4', 'n2-standard-8'],
	        network_tier: 'STANDARD'
	      },
	      storage: {
	        tier: 'custom',
	        size: 200,
	        disk_type: 'pd-ssd'
	      }
	    }
	  })
	}

);
const runner = await response.json();
```

#### Python

```python
import requests

response = requests.post(

	'https://api.warpbuild.com/api/v1/runners',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'name': 'my-gcp-runner',
	    'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
	    'provider_id': 'ee7c619a-c68d-47e5-8385-1aac164cb555',
	    'labels': ['self-hosted', 'linux', 'x64', 'gcp'],
	    'configuration': {
	        'image': 'ubuntu-2404',
	        'capacity_type': 'spot',
	        'byoc_sku': {
	            'arch': 'x64',
	            'is_public': False,
	            'instance_types': ['n2-standard-4', 'n2-standard-8'],
	            'network_tier': 'STANDARD'
	        },
	        'storage': {
	            'tier': 'custom',
	            'size': 200,
	            'disk_type': 'pd-ssd'
	        }
	    }
	}

)
runner = response.json()
```

### 3. Create a Custom Runner on Azure (BYOC)

Bring Your Own Cloud runner on Microsoft Azure.

#### Shell (curl)

```bash

	curl -X POST "https://api.warpbuild.com/api/v1/runners" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "name": "my-azure-runner",
	       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	       "provider_id": "9f77aea2-3162-44b4-b6f0-cdf84ce30a05",
	       "labels": ["self-hosted", "linux", "x64", "azure"],
	       "configuration": {
	         "image": "ubuntu-2404",
	         "capacity_type": "spot",
	         "byoc_sku": {
	           "arch": "x64",
	           "is_public": false,
	           "instance_types": ["Standard_D4s_v3", "Standard_D8s_v3"]
	         },
	         "storage": {
	           "tier": "high",
	           "size": 200,
	           "performance_tier": "P30"
	         }
	       }
	     }'

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners',
	{
	  method: 'POST',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    name: 'my-azure-runner',
	    vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
	    provider_id: '9f77aea2-3162-44b4-b6f0-cdf84ce30a05',
	    labels: ['self-hosted', 'linux', 'x64', 'azure'],
	    configuration: {
	      image: 'ubuntu-2404',
	      capacity_type: 'spot',
	      byoc_sku: {
	        arch: 'x64',
	        is_public: false,
	        instance_types: ['Standard_D4s_v3', 'Standard_D8s_v3']
	      },
	      storage: {
	        tier: 'high',
	        size: 200,
	        performance_tier: 'P30'
	      }
	    }
	  })
	}

);
const runner = await response.json();
```

#### Python

```python
import requests

response = requests.post(

	'https://api.warpbuild.com/api/v1/runners',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'name': 'my-azure-runner',
	    'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
	    'provider_id': '9f77aea2-3162-44b4-b6f0-cdf84ce30a05',
	    'labels': ['self-hosted', 'linux', 'x64', 'azure'],
	    'configuration': {
	        'image': 'ubuntu-2404',
	        'capacity_type': 'spot',
	        'byoc_sku': {
	            'arch': 'x64',
	            'is_public': False,
	            'instance_types': ['Standard_D4s_v3', 'Standard_D8s_v3']
	        },
	        'storage': {
	            'tier': 'high',
	            'size': 200,
	            'performance_tier': 'P30'
	        }
	    }
	}

)
runner = response.json()
```

### 4. Create a Custom Runner with Custom Image

Runner using a custom container image with a specific SKU.

#### Shell (curl)

```bash

	curl -X POST "https://api.warpbuild.com/api/v1/runners" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "name": "warpdev-custom-test-custom-image",
	       "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	       "labels": ["warpdev-custom-test-custom-image"],
	       "configuration": {
	         "sku": "4x-x64-w1kkdpjem73cmowh",
	         "image": "wjqcx6ozzghczk5x",
	         "capacity_type": "ondemand",
	         "storage": {
	           "tier": "low",
	           "size": 150,
	           "iops": 3200,
	           "throughput": 250,
	           "disk_type": "pd-balanced"
	         }
	       }
	     }'

```

#### Example Response

```json

	{
	  "id": "wzvojxk17eo3s1dq",
	  "created_at": "2024-10-09T17:28:02.050974Z",
	  "updated_at": "2024-10-09T17:28:02.050974Z",
	  "name": "warpdev-custom-test-custom-image",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "4x-x64-w1kkdpjem73cmowh",
	    "storage": {
	      "tier": "low",
	      "size": 150,
	      "iops": 3200,
	      "throughput": 250,
	      "disk_type": "pd-balanced",
	      "performance_tier": ""
	    },
	    "image": "wjqcx6ozzghczk5x",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": null,
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": [
	    "warpdev-custom-test-custom-image"
	  ],
	  "active": true,
	  "provider_id": "",
	  "meta": {}
	}

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners',
	{
	  method: 'POST',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    name: 'warpdev-custom-test-custom-image',
	    vcs_integration_id: 'gh-wc0y0ob3oqymfsmj',
	    labels: ['warpdev-custom-test-custom-image'],
	    configuration: {
	      sku: '4x-x64-w1kkdpjem73cmowh',
	      image: 'wjqcx6ozzghczk5x',
	      capacity_type: 'ondemand',
	      storage: {
	        tier: 'low',
	        size: 150,
	        iops: 3200,
	        throughput: 250,
	        disk_type: 'pd-balanced'
	      }
	    }
	  })
	}

);
const runner = await response.json();
```

#### Python

```python
import requests

response = requests.post(

	'https://api.warpbuild.com/api/v1/runners',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'name': 'warpdev-custom-test-custom-image',
	    'vcs_integration_id': 'gh-wc0y0ob3oqymfsmj',
	    'labels': ['warpdev-custom-test-custom-image'],
	    'configuration': {
	        'sku': '4x-x64-w1kkdpjem73cmowh',
	        'image': 'wjqcx6ozzghczk5x',
	        'capacity_type': 'ondemand',
	        'storage': {
	            'tier': 'low',
	            'size': 150,
	            'iops': 3200,
	            'throughput': 250,
	            'disk_type': 'pd-balanced'
	        }
	    }
	}

)
runner = response.json()
```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSetupRunnerRequest
*/
func (a *V1RunnersAPIService) SetupRunner(ctx context.Context) ApiSetupRunnerRequest {
	return ApiSetupRunnerRequest{
		ApiService: a,
		ctx:        ctx,
	}
}

// Execute executes the request
//
//	@return CommonsRunner
func (a *V1RunnersAPIService) SetupRunnerExecute(r ApiSetupRunnerRequest) (*CommonsRunner, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPost
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnersAPIService.SetupRunner")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		var v WarpBuildAPIError
		err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
		if err != nil {
			newErr.error = err.Error()
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
		newErr.model = v
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateRunnerRequest struct {
	ctx        context.Context
	ApiService V1RunnersAPI
	id         string
	body       *CommonsUpdateRunnerInput
}

// update runner body
func (r ApiUpdateRunnerRequest) Body(body CommonsUpdateRunnerInput) ApiUpdateRunnerRequest {
	r.body = &body
	return r
}

func (r ApiUpdateRunnerRequest) Execute() (*CommonsRunner, *http.Response, error) {
	return r.ApiService.UpdateRunnerExecute(r)
}

/*
UpdateRunner Update a runner

Updates an existing runner set configuration. Only the fields specified in the request body will be updated; all other fields remain unchanged.

You can update various aspects of a runner including its name, labels, storage configuration, and capacity type.

## Code Examples

### 1. Update Runner Labels

#### Shell (curl)

```bash

	curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "labels": ["my-runner", "ubuntu", "x64"]
	     }'

```

#### Example Response

```json

	{
	  "id": "wzvojxk17eo3s1dq",
	  "created_at": "2024-10-09T17:28:02.050974Z",
	  "updated_at": "2024-12-25T10:30:00.000000Z",
	  "name": "warpdev-custom-test-custom-image",
	  "vcs_integration_id": "gh-wc0y0ob3oqymfsmj",
	  "configuration": {
	    "sku": "4x-x64-w1kkdpjem73cmowh",
	    "storage": {
	      "tier": "low",
	      "size": 150,
	      "iops": 3200,
	      "throughput": 250,
	      "disk_type": "pd-balanced",
	      "performance_tier": ""
	    },
	    "image": "wjqcx6ozzghczk5x",
	    "capacity_type": "ondemand"
	  },
	  "stock_runner_id": null,
	  "organization_id": "wfmn080eif8rniwq",
	  "labels": [
	    "my-runner",
	    "ubuntu",
	    "x64"
	  ],
	  "active": true,
	  "provider_id": "",
	  "meta": {}
	}

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	{
	  method: 'PUT',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    labels: ['my-runner', 'ubuntu', 'x64']
	  })
	}

);
const updatedRunner = await response.json();
console.log(`Updated labels: ${updatedRunner.labels.join(', ')}`);
```

#### Python

```python
import requests

response = requests.put(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'labels': ['my-runner', 'ubuntu', 'x64']
	}

)
updated_runner = response.json()
print(f"Updated labels: {updated_runner['labels']}")
```

### 2. Update Runner Configuration

#### Shell (curl)

```bash

	curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "configuration": {
	         "sku": "8x-x64-w80f032rccrc9nh2",
	         "capacity_type": "spot",
	         "storage": {
	           "tier": "high",
	           "size": 200
	         }
	       }
	     }'

```

#### TypeScript

```typescript
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	{
	  method: 'PUT',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    configuration: {
	      sku: '8x-x64-w80f032rccrc9nh2',
	      capacity_type: 'spot',
	      storage: {
	        tier: 'high',
	        size: 200
	      }
	    }
	  })
	}

);
const updatedRunner = await response.json();
```

#### Python

```python
import requests

response = requests.put(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'configuration': {
	        'sku': '8x-x64-w80f032rccrc9nh2',
	        'capacity_type': 'spot',
	        'storage': {
	            'tier': 'high',
	            'size': 200
	        }
	    }
	}

)
updated_runner = response.json()
```

### 3. Enable/Disable Runner

#### Shell (curl)

```bash
# Disable a runner

	curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "active": false
	     }'

# Re-enable a runner

	curl -X PUT "https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq" \
	     -H "Authorization: Bearer <your-api-key>" \
	     -H "Content-Type: application/json" \
	     -d '{
	       "active": true
	     }'

```

#### TypeScript

```typescript
// Disable a runner
const response = await fetch(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	{
	  method: 'PUT',
	  headers: {
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	  },
	  body: JSON.stringify({
	    active: false
	  })
	}

);
const updatedRunner = await response.json();
console.log(`Runner active: ${updatedRunner.active}`);
```

#### Python

```python
import requests

# Disable a runner
response = requests.put(

	'https://api.warpbuild.com/api/v1/runners/wzvojxk17eo3s1dq',
	headers={
	    'Authorization': 'Bearer <your-api-key>',
	    'Content-Type': 'application/json'
	},
	json={
	    'active': False
	}

)
updated_runner = response.json()
print(f"Runner active: {updated_runner['active']}")
```

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param id Runner ID
	@return ApiUpdateRunnerRequest
*/
func (a *V1RunnersAPIService) UpdateRunner(ctx context.Context, id string) ApiUpdateRunnerRequest {
	return ApiUpdateRunnerRequest{
		ApiService: a,
		ctx:        ctx,
		id:         id,
	}
}

// Execute executes the request
//
//	@return CommonsRunner
func (a *V1RunnersAPIService) UpdateRunnerExecute(r ApiUpdateRunnerRequest) (*CommonsRunner, *http.Response, error) {
	var (
		localVarHTTPMethod  = http.MethodPatch
		localVarPostBody    interface{}
		formFiles           []formFile
		localVarReturnValue *CommonsRunner
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "V1RunnersAPIService.UpdateRunner")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/runners/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterValueToString(r.id, "id")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.body == nil {
		return localVarReturnValue, nil, reportError("body is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.body
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v WarpBuildAPIError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
			newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
			newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
