/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsWarpbuildSnapshotImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsWarpbuildSnapshotImage{}

// CommonsWarpbuildSnapshotImage struct for CommonsWarpbuildSnapshotImage
type CommonsWarpbuildSnapshotImage struct {
	// AMIID is the ID of the AMI.  +OutputOnly
	AmiId *string `json:"ami_id,omitempty"`
	// CreatorRunnerInstanceID is the ID of the runner instance that created the snapshot. This is populated via the auth token.  +OutputOnly
	CreatorRunnerInstanceId *string `json:"creator_runner_instance_id,omitempty"`
	// Provider is the cloud provider of the snapshot.  +OutputOnly
	Provider *string `json:"provider,omitempty"`
	// SnapshotID is the ID of the snapshot.  +OutputOnly
	SnapshotId *string `json:"snapshot_id,omitempty"`
	// VCSOrganizationName is the name of the VCS organization. This is populated via the auth token.  +OutputOnly
	VcsOrganizationName *string `json:"vcs_organization_name,omitempty"`
	// VCSRefName is the name of the VCS ref. This is populated via the auth token.  +OutputOnly
	VcsRefName *string `json:"vcs_ref_name,omitempty"`
	// VCSRepositoryName is the name of the VCS repository. This is populated via the auth token.  +OutputOnly
	VcsRepositoryName *string `json:"vcs_repository_name,omitempty"`
	// VersionID is the ID of the version. This is used when creating a new version of the snapshot.
	VersionId            *int32 `json:"version_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsWarpbuildSnapshotImage CommonsWarpbuildSnapshotImage

// NewCommonsWarpbuildSnapshotImage instantiates a new CommonsWarpbuildSnapshotImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsWarpbuildSnapshotImage() *CommonsWarpbuildSnapshotImage {
	this := CommonsWarpbuildSnapshotImage{}
	return &this
}

// NewCommonsWarpbuildSnapshotImageWithDefaults instantiates a new CommonsWarpbuildSnapshotImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsWarpbuildSnapshotImageWithDefaults() *CommonsWarpbuildSnapshotImage {
	this := CommonsWarpbuildSnapshotImage{}
	return &this
}

// GetAmiId returns the AmiId field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetAmiId() string {
	if o == nil || IsNil(o.AmiId) {
		var ret string
		return ret
	}
	return *o.AmiId
}

// GetAmiIdOk returns a tuple with the AmiId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetAmiIdOk() (*string, bool) {
	if o == nil || IsNil(o.AmiId) {
		return nil, false
	}
	return o.AmiId, true
}

// HasAmiId returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasAmiId() bool {
	if o != nil && !IsNil(o.AmiId) {
		return true
	}

	return false
}

// SetAmiId gets a reference to the given string and assigns it to the AmiId field.
func (o *CommonsWarpbuildSnapshotImage) SetAmiId(v string) {
	o.AmiId = &v
}

// GetCreatorRunnerInstanceId returns the CreatorRunnerInstanceId field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetCreatorRunnerInstanceId() string {
	if o == nil || IsNil(o.CreatorRunnerInstanceId) {
		var ret string
		return ret
	}
	return *o.CreatorRunnerInstanceId
}

// GetCreatorRunnerInstanceIdOk returns a tuple with the CreatorRunnerInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetCreatorRunnerInstanceIdOk() (*string, bool) {
	if o == nil || IsNil(o.CreatorRunnerInstanceId) {
		return nil, false
	}
	return o.CreatorRunnerInstanceId, true
}

// HasCreatorRunnerInstanceId returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasCreatorRunnerInstanceId() bool {
	if o != nil && !IsNil(o.CreatorRunnerInstanceId) {
		return true
	}

	return false
}

// SetCreatorRunnerInstanceId gets a reference to the given string and assigns it to the CreatorRunnerInstanceId field.
func (o *CommonsWarpbuildSnapshotImage) SetCreatorRunnerInstanceId(v string) {
	o.CreatorRunnerInstanceId = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *CommonsWarpbuildSnapshotImage) SetProvider(v string) {
	o.Provider = &v
}

// GetSnapshotId returns the SnapshotId field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetSnapshotId() string {
	if o == nil || IsNil(o.SnapshotId) {
		var ret string
		return ret
	}
	return *o.SnapshotId
}

// GetSnapshotIdOk returns a tuple with the SnapshotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetSnapshotIdOk() (*string, bool) {
	if o == nil || IsNil(o.SnapshotId) {
		return nil, false
	}
	return o.SnapshotId, true
}

// HasSnapshotId returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasSnapshotId() bool {
	if o != nil && !IsNil(o.SnapshotId) {
		return true
	}

	return false
}

// SetSnapshotId gets a reference to the given string and assigns it to the SnapshotId field.
func (o *CommonsWarpbuildSnapshotImage) SetSnapshotId(v string) {
	o.SnapshotId = &v
}

// GetVcsOrganizationName returns the VcsOrganizationName field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetVcsOrganizationName() string {
	if o == nil || IsNil(o.VcsOrganizationName) {
		var ret string
		return ret
	}
	return *o.VcsOrganizationName
}

// GetVcsOrganizationNameOk returns a tuple with the VcsOrganizationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetVcsOrganizationNameOk() (*string, bool) {
	if o == nil || IsNil(o.VcsOrganizationName) {
		return nil, false
	}
	return o.VcsOrganizationName, true
}

// HasVcsOrganizationName returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasVcsOrganizationName() bool {
	if o != nil && !IsNil(o.VcsOrganizationName) {
		return true
	}

	return false
}

// SetVcsOrganizationName gets a reference to the given string and assigns it to the VcsOrganizationName field.
func (o *CommonsWarpbuildSnapshotImage) SetVcsOrganizationName(v string) {
	o.VcsOrganizationName = &v
}

// GetVcsRefName returns the VcsRefName field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetVcsRefName() string {
	if o == nil || IsNil(o.VcsRefName) {
		var ret string
		return ret
	}
	return *o.VcsRefName
}

// GetVcsRefNameOk returns a tuple with the VcsRefName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetVcsRefNameOk() (*string, bool) {
	if o == nil || IsNil(o.VcsRefName) {
		return nil, false
	}
	return o.VcsRefName, true
}

// HasVcsRefName returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasVcsRefName() bool {
	if o != nil && !IsNil(o.VcsRefName) {
		return true
	}

	return false
}

// SetVcsRefName gets a reference to the given string and assigns it to the VcsRefName field.
func (o *CommonsWarpbuildSnapshotImage) SetVcsRefName(v string) {
	o.VcsRefName = &v
}

// GetVcsRepositoryName returns the VcsRepositoryName field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetVcsRepositoryName() string {
	if o == nil || IsNil(o.VcsRepositoryName) {
		var ret string
		return ret
	}
	return *o.VcsRepositoryName
}

// GetVcsRepositoryNameOk returns a tuple with the VcsRepositoryName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetVcsRepositoryNameOk() (*string, bool) {
	if o == nil || IsNil(o.VcsRepositoryName) {
		return nil, false
	}
	return o.VcsRepositoryName, true
}

// HasVcsRepositoryName returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasVcsRepositoryName() bool {
	if o != nil && !IsNil(o.VcsRepositoryName) {
		return true
	}

	return false
}

// SetVcsRepositoryName gets a reference to the given string and assigns it to the VcsRepositoryName field.
func (o *CommonsWarpbuildSnapshotImage) SetVcsRepositoryName(v string) {
	o.VcsRepositoryName = &v
}

// GetVersionId returns the VersionId field value if set, zero value otherwise.
func (o *CommonsWarpbuildSnapshotImage) GetVersionId() int32 {
	if o == nil || IsNil(o.VersionId) {
		var ret int32
		return ret
	}
	return *o.VersionId
}

// GetVersionIdOk returns a tuple with the VersionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsWarpbuildSnapshotImage) GetVersionIdOk() (*int32, bool) {
	if o == nil || IsNil(o.VersionId) {
		return nil, false
	}
	return o.VersionId, true
}

// HasVersionId returns a boolean if a field has been set.
func (o *CommonsWarpbuildSnapshotImage) HasVersionId() bool {
	if o != nil && !IsNil(o.VersionId) {
		return true
	}

	return false
}

// SetVersionId gets a reference to the given int32 and assigns it to the VersionId field.
func (o *CommonsWarpbuildSnapshotImage) SetVersionId(v int32) {
	o.VersionId = &v
}

func (o CommonsWarpbuildSnapshotImage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsWarpbuildSnapshotImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AmiId) {
		toSerialize["ami_id"] = o.AmiId
	}
	if !IsNil(o.CreatorRunnerInstanceId) {
		toSerialize["creator_runner_instance_id"] = o.CreatorRunnerInstanceId
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.SnapshotId) {
		toSerialize["snapshot_id"] = o.SnapshotId
	}
	if !IsNil(o.VcsOrganizationName) {
		toSerialize["vcs_organization_name"] = o.VcsOrganizationName
	}
	if !IsNil(o.VcsRefName) {
		toSerialize["vcs_ref_name"] = o.VcsRefName
	}
	if !IsNil(o.VcsRepositoryName) {
		toSerialize["vcs_repository_name"] = o.VcsRepositoryName
	}
	if !IsNil(o.VersionId) {
		toSerialize["version_id"] = o.VersionId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsWarpbuildSnapshotImage) UnmarshalJSON(data []byte) (err error) {
	varCommonsWarpbuildSnapshotImage := _CommonsWarpbuildSnapshotImage{}

	err = json.Unmarshal(data, &varCommonsWarpbuildSnapshotImage)

	if err != nil {
		return err
	}

	*o = CommonsWarpbuildSnapshotImage(varCommonsWarpbuildSnapshotImage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ami_id")
		delete(additionalProperties, "creator_runner_instance_id")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "snapshot_id")
		delete(additionalProperties, "vcs_organization_name")
		delete(additionalProperties, "vcs_ref_name")
		delete(additionalProperties, "vcs_repository_name")
		delete(additionalProperties, "version_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsWarpbuildSnapshotImage struct {
	value *CommonsWarpbuildSnapshotImage
	isSet bool
}

func (v NullableCommonsWarpbuildSnapshotImage) Get() *CommonsWarpbuildSnapshotImage {
	return v.value
}

func (v *NullableCommonsWarpbuildSnapshotImage) Set(val *CommonsWarpbuildSnapshotImage) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsWarpbuildSnapshotImage) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsWarpbuildSnapshotImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsWarpbuildSnapshotImage(val *CommonsWarpbuildSnapshotImage) *NullableCommonsWarpbuildSnapshotImage {
	return &NullableCommonsWarpbuildSnapshotImage{value: val, isSet: true}
}

func (v NullableCommonsWarpbuildSnapshotImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsWarpbuildSnapshotImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
