/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CommonsByocAMI type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsByocAMI{}

// CommonsByocAMI struct for CommonsByocAMI
type CommonsByocAMI struct {
	// AmiID is the AWS AMI ID of the customer-owned image.
	AmiId string `json:"ami_id"`
	// RootDeviceName is the root device name of the AMI (e.g. /dev/sda1). Defaults are resolved from the AMI when omitted.
	RootDeviceName       *string `json:"root_device_name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsByocAMI CommonsByocAMI

// NewCommonsByocAMI instantiates a new CommonsByocAMI object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsByocAMI(amiId string) *CommonsByocAMI {
	this := CommonsByocAMI{}
	this.AmiId = amiId
	return &this
}

// NewCommonsByocAMIWithDefaults instantiates a new CommonsByocAMI object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsByocAMIWithDefaults() *CommonsByocAMI {
	this := CommonsByocAMI{}
	return &this
}

// GetAmiId returns the AmiId field value
func (o *CommonsByocAMI) GetAmiId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AmiId
}

// GetAmiIdOk returns a tuple with the AmiId field value
// and a boolean to check if the value has been set.
func (o *CommonsByocAMI) GetAmiIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AmiId, true
}

// SetAmiId sets field value
func (o *CommonsByocAMI) SetAmiId(v string) {
	o.AmiId = v
}

// GetRootDeviceName returns the RootDeviceName field value if set, zero value otherwise.
func (o *CommonsByocAMI) GetRootDeviceName() string {
	if o == nil || IsNil(o.RootDeviceName) {
		var ret string
		return ret
	}
	return *o.RootDeviceName
}

// GetRootDeviceNameOk returns a tuple with the RootDeviceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsByocAMI) GetRootDeviceNameOk() (*string, bool) {
	if o == nil || IsNil(o.RootDeviceName) {
		return nil, false
	}
	return o.RootDeviceName, true
}

// HasRootDeviceName returns a boolean if a field has been set.
func (o *CommonsByocAMI) HasRootDeviceName() bool {
	if o != nil && !IsNil(o.RootDeviceName) {
		return true
	}

	return false
}

// SetRootDeviceName gets a reference to the given string and assigns it to the RootDeviceName field.
func (o *CommonsByocAMI) SetRootDeviceName(v string) {
	o.RootDeviceName = &v
}

func (o CommonsByocAMI) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsByocAMI) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ami_id"] = o.AmiId
	if !IsNil(o.RootDeviceName) {
		toSerialize["root_device_name"] = o.RootDeviceName
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsByocAMI) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ami_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonsByocAMI := _CommonsByocAMI{}

	err = json.Unmarshal(data, &varCommonsByocAMI)

	if err != nil {
		return err
	}

	*o = CommonsByocAMI(varCommonsByocAMI)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ami_id")
		delete(additionalProperties, "root_device_name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsByocAMI struct {
	value *CommonsByocAMI
	isSet bool
}

func (v NullableCommonsByocAMI) Get() *CommonsByocAMI {
	return v.value
}

func (v *NullableCommonsByocAMI) Set(val *CommonsByocAMI) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsByocAMI) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsByocAMI) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsByocAMI(val *CommonsByocAMI) *NullableCommonsByocAMI {
	return &NullableCommonsByocAMI{value: val, isSet: true}
}

func (v NullableCommonsByocAMI) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsByocAMI) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
