/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsEC2Meta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsEC2Meta{}

// CommonsEC2Meta struct for CommonsEC2Meta
type CommonsEC2Meta struct {
	AwsCloudformationStackId *string `json:"aws_cloudformation_stack_id,omitempty"`
	AdditionalProperties     map[string]interface{}
}

type _CommonsEC2Meta CommonsEC2Meta

// NewCommonsEC2Meta instantiates a new CommonsEC2Meta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsEC2Meta() *CommonsEC2Meta {
	this := CommonsEC2Meta{}
	return &this
}

// NewCommonsEC2MetaWithDefaults instantiates a new CommonsEC2Meta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsEC2MetaWithDefaults() *CommonsEC2Meta {
	this := CommonsEC2Meta{}
	return &this
}

// GetAwsCloudformationStackId returns the AwsCloudformationStackId field value if set, zero value otherwise.
func (o *CommonsEC2Meta) GetAwsCloudformationStackId() string {
	if o == nil || IsNil(o.AwsCloudformationStackId) {
		var ret string
		return ret
	}
	return *o.AwsCloudformationStackId
}

// GetAwsCloudformationStackIdOk returns a tuple with the AwsCloudformationStackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Meta) GetAwsCloudformationStackIdOk() (*string, bool) {
	if o == nil || IsNil(o.AwsCloudformationStackId) {
		return nil, false
	}
	return o.AwsCloudformationStackId, true
}

// HasAwsCloudformationStackId returns a boolean if a field has been set.
func (o *CommonsEC2Meta) HasAwsCloudformationStackId() bool {
	if o != nil && !IsNil(o.AwsCloudformationStackId) {
		return true
	}

	return false
}

// SetAwsCloudformationStackId gets a reference to the given string and assigns it to the AwsCloudformationStackId field.
func (o *CommonsEC2Meta) SetAwsCloudformationStackId(v string) {
	o.AwsCloudformationStackId = &v
}

func (o CommonsEC2Meta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsEC2Meta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AwsCloudformationStackId) {
		toSerialize["aws_cloudformation_stack_id"] = o.AwsCloudformationStackId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsEC2Meta) UnmarshalJSON(data []byte) (err error) {
	varCommonsEC2Meta := _CommonsEC2Meta{}

	err = json.Unmarshal(data, &varCommonsEC2Meta)

	if err != nil {
		return err
	}

	*o = CommonsEC2Meta(varCommonsEC2Meta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "aws_cloudformation_stack_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsEC2Meta struct {
	value *CommonsEC2Meta
	isSet bool
}

func (v NullableCommonsEC2Meta) Get() *CommonsEC2Meta {
	return v.value
}

func (v *NullableCommonsEC2Meta) Set(val *CommonsEC2Meta) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsEC2Meta) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsEC2Meta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsEC2Meta(val *CommonsEC2Meta) *NullableCommonsEC2Meta {
	return &NullableCommonsEC2Meta{value: val, isSet: true}
}

func (v NullableCommonsEC2Meta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsEC2Meta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
