/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsStackConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsStackConfigurations{}

// CommonsStackConfigurations struct for CommonsStackConfigurations
type CommonsStackConfigurations struct {
	AvmConfigurations      *CommonsAVMConfigurations      `json:"avm_configurations,omitempty"`
	DefaultTags            *map[string]string             `json:"default_tags,omitempty"`
	Ec2Configurations      *CommonsEC2Configurations      `json:"ec2_configurations,omitempty"`
	GceConfigurations      *CommonsGCEConfigurations      `json:"gce_configurations,omitempty"`
	KubevirtConfigurations *CommonsKubevirtConfigurations `json:"kubevirt_configurations,omitempty"`
	NomadConfigurations    *CommonsNomadConfigurations    `json:"nomad_configurations,omitempty"`
	OrchardConfigurations  *CommonsOrchardConfigurations  `json:"orchard_configurations,omitempty"`
	R2Configurations       *CommonsR2Configurations       `json:"r2_configurations,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _CommonsStackConfigurations CommonsStackConfigurations

// NewCommonsStackConfigurations instantiates a new CommonsStackConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsStackConfigurations() *CommonsStackConfigurations {
	this := CommonsStackConfigurations{}
	return &this
}

// NewCommonsStackConfigurationsWithDefaults instantiates a new CommonsStackConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsStackConfigurationsWithDefaults() *CommonsStackConfigurations {
	this := CommonsStackConfigurations{}
	return &this
}

// GetAvmConfigurations returns the AvmConfigurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetAvmConfigurations() CommonsAVMConfigurations {
	if o == nil || IsNil(o.AvmConfigurations) {
		var ret CommonsAVMConfigurations
		return ret
	}
	return *o.AvmConfigurations
}

// GetAvmConfigurationsOk returns a tuple with the AvmConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetAvmConfigurationsOk() (*CommonsAVMConfigurations, bool) {
	if o == nil || IsNil(o.AvmConfigurations) {
		return nil, false
	}
	return o.AvmConfigurations, true
}

// HasAvmConfigurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasAvmConfigurations() bool {
	if o != nil && !IsNil(o.AvmConfigurations) {
		return true
	}

	return false
}

// SetAvmConfigurations gets a reference to the given CommonsAVMConfigurations and assigns it to the AvmConfigurations field.
func (o *CommonsStackConfigurations) SetAvmConfigurations(v CommonsAVMConfigurations) {
	o.AvmConfigurations = &v
}

// GetDefaultTags returns the DefaultTags field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetDefaultTags() map[string]string {
	if o == nil || IsNil(o.DefaultTags) {
		var ret map[string]string
		return ret
	}
	return *o.DefaultTags
}

// GetDefaultTagsOk returns a tuple with the DefaultTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetDefaultTagsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DefaultTags) {
		return nil, false
	}
	return o.DefaultTags, true
}

// HasDefaultTags returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasDefaultTags() bool {
	if o != nil && !IsNil(o.DefaultTags) {
		return true
	}

	return false
}

// SetDefaultTags gets a reference to the given map[string]string and assigns it to the DefaultTags field.
func (o *CommonsStackConfigurations) SetDefaultTags(v map[string]string) {
	o.DefaultTags = &v
}

// GetEc2Configurations returns the Ec2Configurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetEc2Configurations() CommonsEC2Configurations {
	if o == nil || IsNil(o.Ec2Configurations) {
		var ret CommonsEC2Configurations
		return ret
	}
	return *o.Ec2Configurations
}

// GetEc2ConfigurationsOk returns a tuple with the Ec2Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetEc2ConfigurationsOk() (*CommonsEC2Configurations, bool) {
	if o == nil || IsNil(o.Ec2Configurations) {
		return nil, false
	}
	return o.Ec2Configurations, true
}

// HasEc2Configurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasEc2Configurations() bool {
	if o != nil && !IsNil(o.Ec2Configurations) {
		return true
	}

	return false
}

// SetEc2Configurations gets a reference to the given CommonsEC2Configurations and assigns it to the Ec2Configurations field.
func (o *CommonsStackConfigurations) SetEc2Configurations(v CommonsEC2Configurations) {
	o.Ec2Configurations = &v
}

// GetGceConfigurations returns the GceConfigurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetGceConfigurations() CommonsGCEConfigurations {
	if o == nil || IsNil(o.GceConfigurations) {
		var ret CommonsGCEConfigurations
		return ret
	}
	return *o.GceConfigurations
}

// GetGceConfigurationsOk returns a tuple with the GceConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetGceConfigurationsOk() (*CommonsGCEConfigurations, bool) {
	if o == nil || IsNil(o.GceConfigurations) {
		return nil, false
	}
	return o.GceConfigurations, true
}

// HasGceConfigurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasGceConfigurations() bool {
	if o != nil && !IsNil(o.GceConfigurations) {
		return true
	}

	return false
}

// SetGceConfigurations gets a reference to the given CommonsGCEConfigurations and assigns it to the GceConfigurations field.
func (o *CommonsStackConfigurations) SetGceConfigurations(v CommonsGCEConfigurations) {
	o.GceConfigurations = &v
}

// GetKubevirtConfigurations returns the KubevirtConfigurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetKubevirtConfigurations() CommonsKubevirtConfigurations {
	if o == nil || IsNil(o.KubevirtConfigurations) {
		var ret CommonsKubevirtConfigurations
		return ret
	}
	return *o.KubevirtConfigurations
}

// GetKubevirtConfigurationsOk returns a tuple with the KubevirtConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetKubevirtConfigurationsOk() (*CommonsKubevirtConfigurations, bool) {
	if o == nil || IsNil(o.KubevirtConfigurations) {
		return nil, false
	}
	return o.KubevirtConfigurations, true
}

// HasKubevirtConfigurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasKubevirtConfigurations() bool {
	if o != nil && !IsNil(o.KubevirtConfigurations) {
		return true
	}

	return false
}

// SetKubevirtConfigurations gets a reference to the given CommonsKubevirtConfigurations and assigns it to the KubevirtConfigurations field.
func (o *CommonsStackConfigurations) SetKubevirtConfigurations(v CommonsKubevirtConfigurations) {
	o.KubevirtConfigurations = &v
}

// GetNomadConfigurations returns the NomadConfigurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetNomadConfigurations() CommonsNomadConfigurations {
	if o == nil || IsNil(o.NomadConfigurations) {
		var ret CommonsNomadConfigurations
		return ret
	}
	return *o.NomadConfigurations
}

// GetNomadConfigurationsOk returns a tuple with the NomadConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetNomadConfigurationsOk() (*CommonsNomadConfigurations, bool) {
	if o == nil || IsNil(o.NomadConfigurations) {
		return nil, false
	}
	return o.NomadConfigurations, true
}

// HasNomadConfigurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasNomadConfigurations() bool {
	if o != nil && !IsNil(o.NomadConfigurations) {
		return true
	}

	return false
}

// SetNomadConfigurations gets a reference to the given CommonsNomadConfigurations and assigns it to the NomadConfigurations field.
func (o *CommonsStackConfigurations) SetNomadConfigurations(v CommonsNomadConfigurations) {
	o.NomadConfigurations = &v
}

// GetOrchardConfigurations returns the OrchardConfigurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetOrchardConfigurations() CommonsOrchardConfigurations {
	if o == nil || IsNil(o.OrchardConfigurations) {
		var ret CommonsOrchardConfigurations
		return ret
	}
	return *o.OrchardConfigurations
}

// GetOrchardConfigurationsOk returns a tuple with the OrchardConfigurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetOrchardConfigurationsOk() (*CommonsOrchardConfigurations, bool) {
	if o == nil || IsNil(o.OrchardConfigurations) {
		return nil, false
	}
	return o.OrchardConfigurations, true
}

// HasOrchardConfigurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasOrchardConfigurations() bool {
	if o != nil && !IsNil(o.OrchardConfigurations) {
		return true
	}

	return false
}

// SetOrchardConfigurations gets a reference to the given CommonsOrchardConfigurations and assigns it to the OrchardConfigurations field.
func (o *CommonsStackConfigurations) SetOrchardConfigurations(v CommonsOrchardConfigurations) {
	o.OrchardConfigurations = &v
}

// GetR2Configurations returns the R2Configurations field value if set, zero value otherwise.
func (o *CommonsStackConfigurations) GetR2Configurations() CommonsR2Configurations {
	if o == nil || IsNil(o.R2Configurations) {
		var ret CommonsR2Configurations
		return ret
	}
	return *o.R2Configurations
}

// GetR2ConfigurationsOk returns a tuple with the R2Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStackConfigurations) GetR2ConfigurationsOk() (*CommonsR2Configurations, bool) {
	if o == nil || IsNil(o.R2Configurations) {
		return nil, false
	}
	return o.R2Configurations, true
}

// HasR2Configurations returns a boolean if a field has been set.
func (o *CommonsStackConfigurations) HasR2Configurations() bool {
	if o != nil && !IsNil(o.R2Configurations) {
		return true
	}

	return false
}

// SetR2Configurations gets a reference to the given CommonsR2Configurations and assigns it to the R2Configurations field.
func (o *CommonsStackConfigurations) SetR2Configurations(v CommonsR2Configurations) {
	o.R2Configurations = &v
}

func (o CommonsStackConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsStackConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AvmConfigurations) {
		toSerialize["avm_configurations"] = o.AvmConfigurations
	}
	if !IsNil(o.DefaultTags) {
		toSerialize["default_tags"] = o.DefaultTags
	}
	if !IsNil(o.Ec2Configurations) {
		toSerialize["ec2_configurations"] = o.Ec2Configurations
	}
	if !IsNil(o.GceConfigurations) {
		toSerialize["gce_configurations"] = o.GceConfigurations
	}
	if !IsNil(o.KubevirtConfigurations) {
		toSerialize["kubevirt_configurations"] = o.KubevirtConfigurations
	}
	if !IsNil(o.NomadConfigurations) {
		toSerialize["nomad_configurations"] = o.NomadConfigurations
	}
	if !IsNil(o.OrchardConfigurations) {
		toSerialize["orchard_configurations"] = o.OrchardConfigurations
	}
	if !IsNil(o.R2Configurations) {
		toSerialize["r2_configurations"] = o.R2Configurations
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsStackConfigurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsStackConfigurations := _CommonsStackConfigurations{}

	err = json.Unmarshal(data, &varCommonsStackConfigurations)

	if err != nil {
		return err
	}

	*o = CommonsStackConfigurations(varCommonsStackConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "avm_configurations")
		delete(additionalProperties, "default_tags")
		delete(additionalProperties, "ec2_configurations")
		delete(additionalProperties, "gce_configurations")
		delete(additionalProperties, "kubevirt_configurations")
		delete(additionalProperties, "nomad_configurations")
		delete(additionalProperties, "orchard_configurations")
		delete(additionalProperties, "r2_configurations")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsStackConfigurations struct {
	value *CommonsStackConfigurations
	isSet bool
}

func (v NullableCommonsStackConfigurations) Get() *CommonsStackConfigurations {
	return v.value
}

func (v *NullableCommonsStackConfigurations) Set(val *CommonsStackConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsStackConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsStackConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsStackConfigurations(val *CommonsStackConfigurations) *NullableCommonsStackConfigurations {
	return &NullableCommonsStackConfigurations{value: val, isSet: true}
}

func (v NullableCommonsStackConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsStackConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
