/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsAVMConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsAVMConfigurations{}

// CommonsAVMConfigurations struct for CommonsAVMConfigurations
type CommonsAVMConfigurations struct {
	CacheBucket          *string                `json:"cache_bucket,omitempty"`
	ObservabilityBucket  *string                `json:"observability_bucket,omitempty"`
	ResourceGroup        *string                `json:"resource_group,omitempty"`
	SecurityGroup        *string                `json:"security_group,omitempty"`
	StorageAccount       *string                `json:"storage_account,omitempty"`
	Subnets              []SubnetInput          `json:"subnets,omitempty"`
	TmplParams           map[string]interface{} `json:"tmpl_params,omitempty"`
	Vnet                 *string                `json:"vnet,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsAVMConfigurations CommonsAVMConfigurations

// NewCommonsAVMConfigurations instantiates a new CommonsAVMConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsAVMConfigurations() *CommonsAVMConfigurations {
	this := CommonsAVMConfigurations{}
	return &this
}

// NewCommonsAVMConfigurationsWithDefaults instantiates a new CommonsAVMConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsAVMConfigurationsWithDefaults() *CommonsAVMConfigurations {
	this := CommonsAVMConfigurations{}
	return &this
}

// GetCacheBucket returns the CacheBucket field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetCacheBucket() string {
	if o == nil || IsNil(o.CacheBucket) {
		var ret string
		return ret
	}
	return *o.CacheBucket
}

// GetCacheBucketOk returns a tuple with the CacheBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetCacheBucketOk() (*string, bool) {
	if o == nil || IsNil(o.CacheBucket) {
		return nil, false
	}
	return o.CacheBucket, true
}

// HasCacheBucket returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasCacheBucket() bool {
	if o != nil && !IsNil(o.CacheBucket) {
		return true
	}

	return false
}

// SetCacheBucket gets a reference to the given string and assigns it to the CacheBucket field.
func (o *CommonsAVMConfigurations) SetCacheBucket(v string) {
	o.CacheBucket = &v
}

// GetObservabilityBucket returns the ObservabilityBucket field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetObservabilityBucket() string {
	if o == nil || IsNil(o.ObservabilityBucket) {
		var ret string
		return ret
	}
	return *o.ObservabilityBucket
}

// GetObservabilityBucketOk returns a tuple with the ObservabilityBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetObservabilityBucketOk() (*string, bool) {
	if o == nil || IsNil(o.ObservabilityBucket) {
		return nil, false
	}
	return o.ObservabilityBucket, true
}

// HasObservabilityBucket returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasObservabilityBucket() bool {
	if o != nil && !IsNil(o.ObservabilityBucket) {
		return true
	}

	return false
}

// SetObservabilityBucket gets a reference to the given string and assigns it to the ObservabilityBucket field.
func (o *CommonsAVMConfigurations) SetObservabilityBucket(v string) {
	o.ObservabilityBucket = &v
}

// GetResourceGroup returns the ResourceGroup field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetResourceGroup() string {
	if o == nil || IsNil(o.ResourceGroup) {
		var ret string
		return ret
	}
	return *o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetResourceGroupOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceGroup) {
		return nil, false
	}
	return o.ResourceGroup, true
}

// HasResourceGroup returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasResourceGroup() bool {
	if o != nil && !IsNil(o.ResourceGroup) {
		return true
	}

	return false
}

// SetResourceGroup gets a reference to the given string and assigns it to the ResourceGroup field.
func (o *CommonsAVMConfigurations) SetResourceGroup(v string) {
	o.ResourceGroup = &v
}

// GetSecurityGroup returns the SecurityGroup field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetSecurityGroup() string {
	if o == nil || IsNil(o.SecurityGroup) {
		var ret string
		return ret
	}
	return *o.SecurityGroup
}

// GetSecurityGroupOk returns a tuple with the SecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetSecurityGroupOk() (*string, bool) {
	if o == nil || IsNil(o.SecurityGroup) {
		return nil, false
	}
	return o.SecurityGroup, true
}

// HasSecurityGroup returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasSecurityGroup() bool {
	if o != nil && !IsNil(o.SecurityGroup) {
		return true
	}

	return false
}

// SetSecurityGroup gets a reference to the given string and assigns it to the SecurityGroup field.
func (o *CommonsAVMConfigurations) SetSecurityGroup(v string) {
	o.SecurityGroup = &v
}

// GetStorageAccount returns the StorageAccount field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetStorageAccount() string {
	if o == nil || IsNil(o.StorageAccount) {
		var ret string
		return ret
	}
	return *o.StorageAccount
}

// GetStorageAccountOk returns a tuple with the StorageAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetStorageAccountOk() (*string, bool) {
	if o == nil || IsNil(o.StorageAccount) {
		return nil, false
	}
	return o.StorageAccount, true
}

// HasStorageAccount returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasStorageAccount() bool {
	if o != nil && !IsNil(o.StorageAccount) {
		return true
	}

	return false
}

// SetStorageAccount gets a reference to the given string and assigns it to the StorageAccount field.
func (o *CommonsAVMConfigurations) SetStorageAccount(v string) {
	o.StorageAccount = &v
}

// GetSubnets returns the Subnets field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetSubnets() []SubnetInput {
	if o == nil || IsNil(o.Subnets) {
		var ret []SubnetInput
		return ret
	}
	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetSubnetsOk() ([]SubnetInput, bool) {
	if o == nil || IsNil(o.Subnets) {
		return nil, false
	}
	return o.Subnets, true
}

// HasSubnets returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasSubnets() bool {
	if o != nil && !IsNil(o.Subnets) {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given []SubnetInput and assigns it to the Subnets field.
func (o *CommonsAVMConfigurations) SetSubnets(v []SubnetInput) {
	o.Subnets = v
}

// GetTmplParams returns the TmplParams field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetTmplParams() map[string]interface{} {
	if o == nil || IsNil(o.TmplParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.TmplParams
}

// GetTmplParamsOk returns a tuple with the TmplParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetTmplParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TmplParams) {
		return map[string]interface{}{}, false
	}
	return o.TmplParams, true
}

// HasTmplParams returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasTmplParams() bool {
	if o != nil && !IsNil(o.TmplParams) {
		return true
	}

	return false
}

// SetTmplParams gets a reference to the given map[string]interface{} and assigns it to the TmplParams field.
func (o *CommonsAVMConfigurations) SetTmplParams(v map[string]interface{}) {
	o.TmplParams = v
}

// GetVnet returns the Vnet field value if set, zero value otherwise.
func (o *CommonsAVMConfigurations) GetVnet() string {
	if o == nil || IsNil(o.Vnet) {
		var ret string
		return ret
	}
	return *o.Vnet
}

// GetVnetOk returns a tuple with the Vnet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsAVMConfigurations) GetVnetOk() (*string, bool) {
	if o == nil || IsNil(o.Vnet) {
		return nil, false
	}
	return o.Vnet, true
}

// HasVnet returns a boolean if a field has been set.
func (o *CommonsAVMConfigurations) HasVnet() bool {
	if o != nil && !IsNil(o.Vnet) {
		return true
	}

	return false
}

// SetVnet gets a reference to the given string and assigns it to the Vnet field.
func (o *CommonsAVMConfigurations) SetVnet(v string) {
	o.Vnet = &v
}

func (o CommonsAVMConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsAVMConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CacheBucket) {
		toSerialize["cache_bucket"] = o.CacheBucket
	}
	if !IsNil(o.ObservabilityBucket) {
		toSerialize["observability_bucket"] = o.ObservabilityBucket
	}
	if !IsNil(o.ResourceGroup) {
		toSerialize["resource_group"] = o.ResourceGroup
	}
	if !IsNil(o.SecurityGroup) {
		toSerialize["security_group"] = o.SecurityGroup
	}
	if !IsNil(o.StorageAccount) {
		toSerialize["storage_account"] = o.StorageAccount
	}
	if !IsNil(o.Subnets) {
		toSerialize["subnets"] = o.Subnets
	}
	if !IsNil(o.TmplParams) {
		toSerialize["tmpl_params"] = o.TmplParams
	}
	if !IsNil(o.Vnet) {
		toSerialize["vnet"] = o.Vnet
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsAVMConfigurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsAVMConfigurations := _CommonsAVMConfigurations{}

	err = json.Unmarshal(data, &varCommonsAVMConfigurations)

	if err != nil {
		return err
	}

	*o = CommonsAVMConfigurations(varCommonsAVMConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cache_bucket")
		delete(additionalProperties, "observability_bucket")
		delete(additionalProperties, "resource_group")
		delete(additionalProperties, "security_group")
		delete(additionalProperties, "storage_account")
		delete(additionalProperties, "subnets")
		delete(additionalProperties, "tmpl_params")
		delete(additionalProperties, "vnet")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsAVMConfigurations struct {
	value *CommonsAVMConfigurations
	isSet bool
}

func (v NullableCommonsAVMConfigurations) Get() *CommonsAVMConfigurations {
	return v.value
}

func (v *NullableCommonsAVMConfigurations) Set(val *CommonsAVMConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsAVMConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsAVMConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsAVMConfigurations(val *CommonsAVMConfigurations) *NullableCommonsAVMConfigurations {
	return &NullableCommonsAVMConfigurations{value: val, isSet: true}
}

func (v NullableCommonsAVMConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsAVMConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
