/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsPoolListOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsPoolListOutput{}

// CommonsPoolListOutput struct for CommonsPoolListOutput
type CommonsPoolListOutput struct {
	Items                []CommonsRunnerPool `json:"items,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsPoolListOutput CommonsPoolListOutput

// NewCommonsPoolListOutput instantiates a new CommonsPoolListOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsPoolListOutput() *CommonsPoolListOutput {
	this := CommonsPoolListOutput{}
	return &this
}

// NewCommonsPoolListOutputWithDefaults instantiates a new CommonsPoolListOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsPoolListOutputWithDefaults() *CommonsPoolListOutput {
	this := CommonsPoolListOutput{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *CommonsPoolListOutput) GetItems() []CommonsRunnerPool {
	if o == nil || IsNil(o.Items) {
		var ret []CommonsRunnerPool
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsPoolListOutput) GetItemsOk() ([]CommonsRunnerPool, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *CommonsPoolListOutput) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []CommonsRunnerPool and assigns it to the Items field.
func (o *CommonsPoolListOutput) SetItems(v []CommonsRunnerPool) {
	o.Items = v
}

func (o CommonsPoolListOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsPoolListOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsPoolListOutput) UnmarshalJSON(data []byte) (err error) {
	varCommonsPoolListOutput := _CommonsPoolListOutput{}

	err = json.Unmarshal(data, &varCommonsPoolListOutput)

	if err != nil {
		return err
	}

	*o = CommonsPoolListOutput(varCommonsPoolListOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsPoolListOutput struct {
	value *CommonsPoolListOutput
	isSet bool
}

func (v NullableCommonsPoolListOutput) Get() *CommonsPoolListOutput {
	return v.value
}

func (v *NullableCommonsPoolListOutput) Set(val *CommonsPoolListOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsPoolListOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsPoolListOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsPoolListOutput(val *CommonsPoolListOutput) *NullableCommonsPoolListOutput {
	return &NullableCommonsPoolListOutput{value: val, isSet: true}
}

func (v NullableCommonsPoolListOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsPoolListOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
