/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CommonsStack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsStack{}

// CommonsStack struct for CommonsStack
type CommonsStack struct {
	Alias                *string                     `json:"alias,omitempty"`
	Configurations       *CommonsStackConfigurations `json:"configurations,omitempty"`
	ConnectionId         *string                     `json:"connection_id,omitempty"`
	CreatedAt            *string                     `json:"created_at,omitempty"`
	Id                   *string                     `json:"id,omitempty"`
	Kind                 string                      `json:"kind"`
	LastReconciledAt     *string                     `json:"last_reconciled_at,omitempty"`
	LatestVersion        *string                     `json:"latest_version,omitempty"`
	Meta                 *CommonsKindMeta            `json:"meta,omitempty"`
	OnboardingMode       *string                     `json:"onboarding_mode,omitempty"`
	OrganizationId       *string                     `json:"organization_id,omitempty"`
	Region               *string                     `json:"region,omitempty"`
	Status               *string                     `json:"status,omitempty"`
	Version              *string                     `json:"version,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsStack CommonsStack

// NewCommonsStack instantiates a new CommonsStack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsStack(kind string) *CommonsStack {
	this := CommonsStack{}
	this.Kind = kind
	return &this
}

// NewCommonsStackWithDefaults instantiates a new CommonsStack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsStackWithDefaults() *CommonsStack {
	this := CommonsStack{}
	return &this
}

// GetAlias returns the Alias field value if set, zero value otherwise.
func (o *CommonsStack) GetAlias() string {
	if o == nil || IsNil(o.Alias) {
		var ret string
		return ret
	}
	return *o.Alias
}

// GetAliasOk returns a tuple with the Alias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetAliasOk() (*string, bool) {
	if o == nil || IsNil(o.Alias) {
		return nil, false
	}
	return o.Alias, true
}

// HasAlias returns a boolean if a field has been set.
func (o *CommonsStack) HasAlias() bool {
	if o != nil && !IsNil(o.Alias) {
		return true
	}

	return false
}

// SetAlias gets a reference to the given string and assigns it to the Alias field.
func (o *CommonsStack) SetAlias(v string) {
	o.Alias = &v
}

// GetConfigurations returns the Configurations field value if set, zero value otherwise.
func (o *CommonsStack) GetConfigurations() CommonsStackConfigurations {
	if o == nil || IsNil(o.Configurations) {
		var ret CommonsStackConfigurations
		return ret
	}
	return *o.Configurations
}

// GetConfigurationsOk returns a tuple with the Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetConfigurationsOk() (*CommonsStackConfigurations, bool) {
	if o == nil || IsNil(o.Configurations) {
		return nil, false
	}
	return o.Configurations, true
}

// HasConfigurations returns a boolean if a field has been set.
func (o *CommonsStack) HasConfigurations() bool {
	if o != nil && !IsNil(o.Configurations) {
		return true
	}

	return false
}

// SetConfigurations gets a reference to the given CommonsStackConfigurations and assigns it to the Configurations field.
func (o *CommonsStack) SetConfigurations(v CommonsStackConfigurations) {
	o.Configurations = &v
}

// GetConnectionId returns the ConnectionId field value if set, zero value otherwise.
func (o *CommonsStack) GetConnectionId() string {
	if o == nil || IsNil(o.ConnectionId) {
		var ret string
		return ret
	}
	return *o.ConnectionId
}

// GetConnectionIdOk returns a tuple with the ConnectionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetConnectionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ConnectionId) {
		return nil, false
	}
	return o.ConnectionId, true
}

// HasConnectionId returns a boolean if a field has been set.
func (o *CommonsStack) HasConnectionId() bool {
	if o != nil && !IsNil(o.ConnectionId) {
		return true
	}

	return false
}

// SetConnectionId gets a reference to the given string and assigns it to the ConnectionId field.
func (o *CommonsStack) SetConnectionId(v string) {
	o.ConnectionId = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CommonsStack) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CommonsStack) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CommonsStack) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CommonsStack) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CommonsStack) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CommonsStack) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value
func (o *CommonsStack) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *CommonsStack) SetKind(v string) {
	o.Kind = v
}

// GetLastReconciledAt returns the LastReconciledAt field value if set, zero value otherwise.
func (o *CommonsStack) GetLastReconciledAt() string {
	if o == nil || IsNil(o.LastReconciledAt) {
		var ret string
		return ret
	}
	return *o.LastReconciledAt
}

// GetLastReconciledAtOk returns a tuple with the LastReconciledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetLastReconciledAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastReconciledAt) {
		return nil, false
	}
	return o.LastReconciledAt, true
}

// HasLastReconciledAt returns a boolean if a field has been set.
func (o *CommonsStack) HasLastReconciledAt() bool {
	if o != nil && !IsNil(o.LastReconciledAt) {
		return true
	}

	return false
}

// SetLastReconciledAt gets a reference to the given string and assigns it to the LastReconciledAt field.
func (o *CommonsStack) SetLastReconciledAt(v string) {
	o.LastReconciledAt = &v
}

// GetLatestVersion returns the LatestVersion field value if set, zero value otherwise.
func (o *CommonsStack) GetLatestVersion() string {
	if o == nil || IsNil(o.LatestVersion) {
		var ret string
		return ret
	}
	return *o.LatestVersion
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetLatestVersionOk() (*string, bool) {
	if o == nil || IsNil(o.LatestVersion) {
		return nil, false
	}
	return o.LatestVersion, true
}

// HasLatestVersion returns a boolean if a field has been set.
func (o *CommonsStack) HasLatestVersion() bool {
	if o != nil && !IsNil(o.LatestVersion) {
		return true
	}

	return false
}

// SetLatestVersion gets a reference to the given string and assigns it to the LatestVersion field.
func (o *CommonsStack) SetLatestVersion(v string) {
	o.LatestVersion = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *CommonsStack) GetMeta() CommonsKindMeta {
	if o == nil || IsNil(o.Meta) {
		var ret CommonsKindMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetMetaOk() (*CommonsKindMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *CommonsStack) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given CommonsKindMeta and assigns it to the Meta field.
func (o *CommonsStack) SetMeta(v CommonsKindMeta) {
	o.Meta = &v
}

// GetOnboardingMode returns the OnboardingMode field value if set, zero value otherwise.
func (o *CommonsStack) GetOnboardingMode() string {
	if o == nil || IsNil(o.OnboardingMode) {
		var ret string
		return ret
	}
	return *o.OnboardingMode
}

// GetOnboardingModeOk returns a tuple with the OnboardingMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetOnboardingModeOk() (*string, bool) {
	if o == nil || IsNil(o.OnboardingMode) {
		return nil, false
	}
	return o.OnboardingMode, true
}

// HasOnboardingMode returns a boolean if a field has been set.
func (o *CommonsStack) HasOnboardingMode() bool {
	if o != nil && !IsNil(o.OnboardingMode) {
		return true
	}

	return false
}

// SetOnboardingMode gets a reference to the given string and assigns it to the OnboardingMode field.
func (o *CommonsStack) SetOnboardingMode(v string) {
	o.OnboardingMode = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CommonsStack) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CommonsStack) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *CommonsStack) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *CommonsStack) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *CommonsStack) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *CommonsStack) SetRegion(v string) {
	o.Region = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CommonsStack) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CommonsStack) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CommonsStack) SetStatus(v string) {
	o.Status = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *CommonsStack) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsStack) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *CommonsStack) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *CommonsStack) SetVersion(v string) {
	o.Version = &v
}

func (o CommonsStack) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsStack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Alias) {
		toSerialize["alias"] = o.Alias
	}
	if !IsNil(o.Configurations) {
		toSerialize["configurations"] = o.Configurations
	}
	if !IsNil(o.ConnectionId) {
		toSerialize["connection_id"] = o.ConnectionId
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["kind"] = o.Kind
	if !IsNil(o.LastReconciledAt) {
		toSerialize["last_reconciled_at"] = o.LastReconciledAt
	}
	if !IsNil(o.LatestVersion) {
		toSerialize["latest_version"] = o.LatestVersion
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	if !IsNil(o.OnboardingMode) {
		toSerialize["onboarding_mode"] = o.OnboardingMode
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsStack) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonsStack := _CommonsStack{}

	err = json.Unmarshal(data, &varCommonsStack)

	if err != nil {
		return err
	}

	*o = CommonsStack(varCommonsStack)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alias")
		delete(additionalProperties, "configurations")
		delete(additionalProperties, "connection_id")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "id")
		delete(additionalProperties, "kind")
		delete(additionalProperties, "last_reconciled_at")
		delete(additionalProperties, "latest_version")
		delete(additionalProperties, "meta")
		delete(additionalProperties, "onboarding_mode")
		delete(additionalProperties, "organization_id")
		delete(additionalProperties, "region")
		delete(additionalProperties, "status")
		delete(additionalProperties, "version")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsStack struct {
	value *CommonsStack
	isSet bool
}

func (v NullableCommonsStack) Get() *CommonsStack {
	return v.value
}

func (v *NullableCommonsStack) Set(val *CommonsStack) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsStack) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsStack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsStack(val *CommonsStack) *NullableCommonsStack {
	return &NullableCommonsStack{value: val, isSet: true}
}

func (v NullableCommonsStack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsStack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
