/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CommonsCreateRunnerImageInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsCreateRunnerImageInput{}

// CommonsCreateRunnerImageInput struct for CommonsCreateRunnerImageInput
type CommonsCreateRunnerImageInput struct {
	// Alias is the human-friendly name of the image. Unique within the organization and immutable after creation.
	Alias string `json:"alias"`
	// Arch is the CPU architecture. For byoc_ami images this is derived from the AMI when available and may be omitted.
	Arch                 *string                      `json:"arch,omitempty"`
	ByocAmi              *CommonsByocAMI              `json:"byoc_ami,omitempty"`
	ContainerRunnerImage *CommonsContainerRunnerImage `json:"container_runner_image,omitempty"`
	Hooks                []CommonsRunnerImageHook     `json:"hooks,omitempty"`
	// OS of the image. For byoc_ami images this is derived from the AMI and may be omitted.
	Os                      *string                     `json:"os,omitempty"`
	RunnerImagePullSecretId *string                     `json:"runner_image_pull_secret_id,omitempty"`
	Settings                *CommonsRunnerImageSettings `json:"settings,omitempty"`
	// StackID is the infrastructure stack (kind + region, e.g. an EC2 stack) the image belongs to. Required for byoc_ami; must be omitted for container images.
	StackId *string `json:"stack_id,omitempty"`
	// Type determines which of the type-specific payloads below is used.
	Type                   string                         `json:"type"`
	WarpbuildSnapshotImage *CommonsWarpbuildSnapshotImage `json:"warpbuild_snapshot_image,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _CommonsCreateRunnerImageInput CommonsCreateRunnerImageInput

// NewCommonsCreateRunnerImageInput instantiates a new CommonsCreateRunnerImageInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsCreateRunnerImageInput(alias string, type_ string) *CommonsCreateRunnerImageInput {
	this := CommonsCreateRunnerImageInput{}
	this.Alias = alias
	this.Type = type_
	return &this
}

// NewCommonsCreateRunnerImageInputWithDefaults instantiates a new CommonsCreateRunnerImageInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsCreateRunnerImageInputWithDefaults() *CommonsCreateRunnerImageInput {
	this := CommonsCreateRunnerImageInput{}
	return &this
}

// GetAlias returns the Alias field value
func (o *CommonsCreateRunnerImageInput) GetAlias() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Alias
}

// GetAliasOk returns a tuple with the Alias field value
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetAliasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Alias, true
}

// SetAlias sets field value
func (o *CommonsCreateRunnerImageInput) SetAlias(v string) {
	o.Alias = v
}

// GetArch returns the Arch field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetArch() string {
	if o == nil || IsNil(o.Arch) {
		var ret string
		return ret
	}
	return *o.Arch
}

// GetArchOk returns a tuple with the Arch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetArchOk() (*string, bool) {
	if o == nil || IsNil(o.Arch) {
		return nil, false
	}
	return o.Arch, true
}

// HasArch returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasArch() bool {
	if o != nil && !IsNil(o.Arch) {
		return true
	}

	return false
}

// SetArch gets a reference to the given string and assigns it to the Arch field.
func (o *CommonsCreateRunnerImageInput) SetArch(v string) {
	o.Arch = &v
}

// GetByocAmi returns the ByocAmi field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetByocAmi() CommonsByocAMI {
	if o == nil || IsNil(o.ByocAmi) {
		var ret CommonsByocAMI
		return ret
	}
	return *o.ByocAmi
}

// GetByocAmiOk returns a tuple with the ByocAmi field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetByocAmiOk() (*CommonsByocAMI, bool) {
	if o == nil || IsNil(o.ByocAmi) {
		return nil, false
	}
	return o.ByocAmi, true
}

// HasByocAmi returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasByocAmi() bool {
	if o != nil && !IsNil(o.ByocAmi) {
		return true
	}

	return false
}

// SetByocAmi gets a reference to the given CommonsByocAMI and assigns it to the ByocAmi field.
func (o *CommonsCreateRunnerImageInput) SetByocAmi(v CommonsByocAMI) {
	o.ByocAmi = &v
}

// GetContainerRunnerImage returns the ContainerRunnerImage field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetContainerRunnerImage() CommonsContainerRunnerImage {
	if o == nil || IsNil(o.ContainerRunnerImage) {
		var ret CommonsContainerRunnerImage
		return ret
	}
	return *o.ContainerRunnerImage
}

// GetContainerRunnerImageOk returns a tuple with the ContainerRunnerImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetContainerRunnerImageOk() (*CommonsContainerRunnerImage, bool) {
	if o == nil || IsNil(o.ContainerRunnerImage) {
		return nil, false
	}
	return o.ContainerRunnerImage, true
}

// HasContainerRunnerImage returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasContainerRunnerImage() bool {
	if o != nil && !IsNil(o.ContainerRunnerImage) {
		return true
	}

	return false
}

// SetContainerRunnerImage gets a reference to the given CommonsContainerRunnerImage and assigns it to the ContainerRunnerImage field.
func (o *CommonsCreateRunnerImageInput) SetContainerRunnerImage(v CommonsContainerRunnerImage) {
	o.ContainerRunnerImage = &v
}

// GetHooks returns the Hooks field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetHooks() []CommonsRunnerImageHook {
	if o == nil || IsNil(o.Hooks) {
		var ret []CommonsRunnerImageHook
		return ret
	}
	return o.Hooks
}

// GetHooksOk returns a tuple with the Hooks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetHooksOk() ([]CommonsRunnerImageHook, bool) {
	if o == nil || IsNil(o.Hooks) {
		return nil, false
	}
	return o.Hooks, true
}

// HasHooks returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasHooks() bool {
	if o != nil && !IsNil(o.Hooks) {
		return true
	}

	return false
}

// SetHooks gets a reference to the given []CommonsRunnerImageHook and assigns it to the Hooks field.
func (o *CommonsCreateRunnerImageInput) SetHooks(v []CommonsRunnerImageHook) {
	o.Hooks = v
}

// GetOs returns the Os field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetOs() string {
	if o == nil || IsNil(o.Os) {
		var ret string
		return ret
	}
	return *o.Os
}

// GetOsOk returns a tuple with the Os field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetOsOk() (*string, bool) {
	if o == nil || IsNil(o.Os) {
		return nil, false
	}
	return o.Os, true
}

// HasOs returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasOs() bool {
	if o != nil && !IsNil(o.Os) {
		return true
	}

	return false
}

// SetOs gets a reference to the given string and assigns it to the Os field.
func (o *CommonsCreateRunnerImageInput) SetOs(v string) {
	o.Os = &v
}

// GetRunnerImagePullSecretId returns the RunnerImagePullSecretId field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetRunnerImagePullSecretId() string {
	if o == nil || IsNil(o.RunnerImagePullSecretId) {
		var ret string
		return ret
	}
	return *o.RunnerImagePullSecretId
}

// GetRunnerImagePullSecretIdOk returns a tuple with the RunnerImagePullSecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetRunnerImagePullSecretIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerImagePullSecretId) {
		return nil, false
	}
	return o.RunnerImagePullSecretId, true
}

// HasRunnerImagePullSecretId returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasRunnerImagePullSecretId() bool {
	if o != nil && !IsNil(o.RunnerImagePullSecretId) {
		return true
	}

	return false
}

// SetRunnerImagePullSecretId gets a reference to the given string and assigns it to the RunnerImagePullSecretId field.
func (o *CommonsCreateRunnerImageInput) SetRunnerImagePullSecretId(v string) {
	o.RunnerImagePullSecretId = &v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetSettings() CommonsRunnerImageSettings {
	if o == nil || IsNil(o.Settings) {
		var ret CommonsRunnerImageSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetSettingsOk() (*CommonsRunnerImageSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given CommonsRunnerImageSettings and assigns it to the Settings field.
func (o *CommonsCreateRunnerImageInput) SetSettings(v CommonsRunnerImageSettings) {
	o.Settings = &v
}

// GetStackId returns the StackId field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetStackId() string {
	if o == nil || IsNil(o.StackId) {
		var ret string
		return ret
	}
	return *o.StackId
}

// GetStackIdOk returns a tuple with the StackId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetStackIdOk() (*string, bool) {
	if o == nil || IsNil(o.StackId) {
		return nil, false
	}
	return o.StackId, true
}

// HasStackId returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasStackId() bool {
	if o != nil && !IsNil(o.StackId) {
		return true
	}

	return false
}

// SetStackId gets a reference to the given string and assigns it to the StackId field.
func (o *CommonsCreateRunnerImageInput) SetStackId(v string) {
	o.StackId = &v
}

// GetType returns the Type field value
func (o *CommonsCreateRunnerImageInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CommonsCreateRunnerImageInput) SetType(v string) {
	o.Type = v
}

// GetWarpbuildSnapshotImage returns the WarpbuildSnapshotImage field value if set, zero value otherwise.
func (o *CommonsCreateRunnerImageInput) GetWarpbuildSnapshotImage() CommonsWarpbuildSnapshotImage {
	if o == nil || IsNil(o.WarpbuildSnapshotImage) {
		var ret CommonsWarpbuildSnapshotImage
		return ret
	}
	return *o.WarpbuildSnapshotImage
}

// GetWarpbuildSnapshotImageOk returns a tuple with the WarpbuildSnapshotImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsCreateRunnerImageInput) GetWarpbuildSnapshotImageOk() (*CommonsWarpbuildSnapshotImage, bool) {
	if o == nil || IsNil(o.WarpbuildSnapshotImage) {
		return nil, false
	}
	return o.WarpbuildSnapshotImage, true
}

// HasWarpbuildSnapshotImage returns a boolean if a field has been set.
func (o *CommonsCreateRunnerImageInput) HasWarpbuildSnapshotImage() bool {
	if o != nil && !IsNil(o.WarpbuildSnapshotImage) {
		return true
	}

	return false
}

// SetWarpbuildSnapshotImage gets a reference to the given CommonsWarpbuildSnapshotImage and assigns it to the WarpbuildSnapshotImage field.
func (o *CommonsCreateRunnerImageInput) SetWarpbuildSnapshotImage(v CommonsWarpbuildSnapshotImage) {
	o.WarpbuildSnapshotImage = &v
}

func (o CommonsCreateRunnerImageInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsCreateRunnerImageInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["alias"] = o.Alias
	if !IsNil(o.Arch) {
		toSerialize["arch"] = o.Arch
	}
	if !IsNil(o.ByocAmi) {
		toSerialize["byoc_ami"] = o.ByocAmi
	}
	if !IsNil(o.ContainerRunnerImage) {
		toSerialize["container_runner_image"] = o.ContainerRunnerImage
	}
	if !IsNil(o.Hooks) {
		toSerialize["hooks"] = o.Hooks
	}
	if !IsNil(o.Os) {
		toSerialize["os"] = o.Os
	}
	if !IsNil(o.RunnerImagePullSecretId) {
		toSerialize["runner_image_pull_secret_id"] = o.RunnerImagePullSecretId
	}
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.StackId) {
		toSerialize["stack_id"] = o.StackId
	}
	toSerialize["type"] = o.Type
	if !IsNil(o.WarpbuildSnapshotImage) {
		toSerialize["warpbuild_snapshot_image"] = o.WarpbuildSnapshotImage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsCreateRunnerImageInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"alias",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonsCreateRunnerImageInput := _CommonsCreateRunnerImageInput{}

	err = json.Unmarshal(data, &varCommonsCreateRunnerImageInput)

	if err != nil {
		return err
	}

	*o = CommonsCreateRunnerImageInput(varCommonsCreateRunnerImageInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "alias")
		delete(additionalProperties, "arch")
		delete(additionalProperties, "byoc_ami")
		delete(additionalProperties, "container_runner_image")
		delete(additionalProperties, "hooks")
		delete(additionalProperties, "os")
		delete(additionalProperties, "runner_image_pull_secret_id")
		delete(additionalProperties, "settings")
		delete(additionalProperties, "stack_id")
		delete(additionalProperties, "type")
		delete(additionalProperties, "warpbuild_snapshot_image")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsCreateRunnerImageInput struct {
	value *CommonsCreateRunnerImageInput
	isSet bool
}

func (v NullableCommonsCreateRunnerImageInput) Get() *CommonsCreateRunnerImageInput {
	return v.value
}

func (v *NullableCommonsCreateRunnerImageInput) Set(val *CommonsCreateRunnerImageInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsCreateRunnerImageInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsCreateRunnerImageInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsCreateRunnerImageInput(val *CommonsCreateRunnerImageInput) *NullableCommonsCreateRunnerImageInput {
	return &NullableCommonsCreateRunnerImageInput{value: val, isSet: true}
}

func (v NullableCommonsCreateRunnerImageInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsCreateRunnerImageInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
