/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsR2Configurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsR2Configurations{}

// CommonsR2Configurations struct for CommonsR2Configurations
type CommonsR2Configurations struct {
	AccessKey       *string `json:"access_key,omitempty"`
	AccessKeySecret *string `json:"access_key_secret,omitempty"`
	AccountId       *string `json:"account_id,omitempty"`
	// Distinct R2 buckets (eu vs. us) are separate stack rows, matching the per-stack-account model above.
	CacheBucket          *string `json:"cache_bucket,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsR2Configurations CommonsR2Configurations

// NewCommonsR2Configurations instantiates a new CommonsR2Configurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsR2Configurations() *CommonsR2Configurations {
	this := CommonsR2Configurations{}
	return &this
}

// NewCommonsR2ConfigurationsWithDefaults instantiates a new CommonsR2Configurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsR2ConfigurationsWithDefaults() *CommonsR2Configurations {
	this := CommonsR2Configurations{}
	return &this
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *CommonsR2Configurations) GetAccessKey() string {
	if o == nil || IsNil(o.AccessKey) {
		var ret string
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsR2Configurations) GetAccessKeyOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKey) {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *CommonsR2Configurations) HasAccessKey() bool {
	if o != nil && !IsNil(o.AccessKey) {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given string and assigns it to the AccessKey field.
func (o *CommonsR2Configurations) SetAccessKey(v string) {
	o.AccessKey = &v
}

// GetAccessKeySecret returns the AccessKeySecret field value if set, zero value otherwise.
func (o *CommonsR2Configurations) GetAccessKeySecret() string {
	if o == nil || IsNil(o.AccessKeySecret) {
		var ret string
		return ret
	}
	return *o.AccessKeySecret
}

// GetAccessKeySecretOk returns a tuple with the AccessKeySecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsR2Configurations) GetAccessKeySecretOk() (*string, bool) {
	if o == nil || IsNil(o.AccessKeySecret) {
		return nil, false
	}
	return o.AccessKeySecret, true
}

// HasAccessKeySecret returns a boolean if a field has been set.
func (o *CommonsR2Configurations) HasAccessKeySecret() bool {
	if o != nil && !IsNil(o.AccessKeySecret) {
		return true
	}

	return false
}

// SetAccessKeySecret gets a reference to the given string and assigns it to the AccessKeySecret field.
func (o *CommonsR2Configurations) SetAccessKeySecret(v string) {
	o.AccessKeySecret = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CommonsR2Configurations) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsR2Configurations) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CommonsR2Configurations) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CommonsR2Configurations) SetAccountId(v string) {
	o.AccountId = &v
}

// GetCacheBucket returns the CacheBucket field value if set, zero value otherwise.
func (o *CommonsR2Configurations) GetCacheBucket() string {
	if o == nil || IsNil(o.CacheBucket) {
		var ret string
		return ret
	}
	return *o.CacheBucket
}

// GetCacheBucketOk returns a tuple with the CacheBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsR2Configurations) GetCacheBucketOk() (*string, bool) {
	if o == nil || IsNil(o.CacheBucket) {
		return nil, false
	}
	return o.CacheBucket, true
}

// HasCacheBucket returns a boolean if a field has been set.
func (o *CommonsR2Configurations) HasCacheBucket() bool {
	if o != nil && !IsNil(o.CacheBucket) {
		return true
	}

	return false
}

// SetCacheBucket gets a reference to the given string and assigns it to the CacheBucket field.
func (o *CommonsR2Configurations) SetCacheBucket(v string) {
	o.CacheBucket = &v
}

func (o CommonsR2Configurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsR2Configurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccessKey) {
		toSerialize["access_key"] = o.AccessKey
	}
	if !IsNil(o.AccessKeySecret) {
		toSerialize["access_key_secret"] = o.AccessKeySecret
	}
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if !IsNil(o.CacheBucket) {
		toSerialize["cache_bucket"] = o.CacheBucket
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsR2Configurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsR2Configurations := _CommonsR2Configurations{}

	err = json.Unmarshal(data, &varCommonsR2Configurations)

	if err != nil {
		return err
	}

	*o = CommonsR2Configurations(varCommonsR2Configurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "access_key")
		delete(additionalProperties, "access_key_secret")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "cache_bucket")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsR2Configurations struct {
	value *CommonsR2Configurations
	isSet bool
}

func (v NullableCommonsR2Configurations) Get() *CommonsR2Configurations {
	return v.value
}

func (v *NullableCommonsR2Configurations) Set(val *CommonsR2Configurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsR2Configurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsR2Configurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsR2Configurations(val *CommonsR2Configurations) *NullableCommonsR2Configurations {
	return &NullableCommonsR2Configurations{value: val, isSet: true}
}

func (v NullableCommonsR2Configurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsR2Configurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
