/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
	"fmt"
)

// checks if the CommonsListRunnerImagesOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsListRunnerImagesOutput{}

// CommonsListRunnerImagesOutput struct for CommonsListRunnerImagesOutput
type CommonsListRunnerImagesOutput struct {
	NextPage             *int32               `json:"next_page,omitempty"`
	Page                 *int32               `json:"page,omitempty"`
	PerPage              *int32               `json:"per_page,omitempty"`
	RunnerImages         []CommonsRunnerImage `json:"runner_images"`
	TotalItems           *int32               `json:"total_items,omitempty"`
	TotalPages           *int32               `json:"total_pages,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsListRunnerImagesOutput CommonsListRunnerImagesOutput

// NewCommonsListRunnerImagesOutput instantiates a new CommonsListRunnerImagesOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsListRunnerImagesOutput(runnerImages []CommonsRunnerImage) *CommonsListRunnerImagesOutput {
	this := CommonsListRunnerImagesOutput{}
	this.RunnerImages = runnerImages
	return &this
}

// NewCommonsListRunnerImagesOutputWithDefaults instantiates a new CommonsListRunnerImagesOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsListRunnerImagesOutputWithDefaults() *CommonsListRunnerImagesOutput {
	this := CommonsListRunnerImagesOutput{}
	return &this
}

// GetNextPage returns the NextPage field value if set, zero value otherwise.
func (o *CommonsListRunnerImagesOutput) GetNextPage() int32 {
	if o == nil || IsNil(o.NextPage) {
		var ret int32
		return ret
	}
	return *o.NextPage
}

// GetNextPageOk returns a tuple with the NextPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetNextPageOk() (*int32, bool) {
	if o == nil || IsNil(o.NextPage) {
		return nil, false
	}
	return o.NextPage, true
}

// HasNextPage returns a boolean if a field has been set.
func (o *CommonsListRunnerImagesOutput) HasNextPage() bool {
	if o != nil && !IsNil(o.NextPage) {
		return true
	}

	return false
}

// SetNextPage gets a reference to the given int32 and assigns it to the NextPage field.
func (o *CommonsListRunnerImagesOutput) SetNextPage(v int32) {
	o.NextPage = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *CommonsListRunnerImagesOutput) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *CommonsListRunnerImagesOutput) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *CommonsListRunnerImagesOutput) SetPage(v int32) {
	o.Page = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *CommonsListRunnerImagesOutput) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *CommonsListRunnerImagesOutput) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *CommonsListRunnerImagesOutput) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetRunnerImages returns the RunnerImages field value
func (o *CommonsListRunnerImagesOutput) GetRunnerImages() []CommonsRunnerImage {
	if o == nil {
		var ret []CommonsRunnerImage
		return ret
	}

	return o.RunnerImages
}

// GetRunnerImagesOk returns a tuple with the RunnerImages field value
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetRunnerImagesOk() ([]CommonsRunnerImage, bool) {
	if o == nil {
		return nil, false
	}
	return o.RunnerImages, true
}

// SetRunnerImages sets field value
func (o *CommonsListRunnerImagesOutput) SetRunnerImages(v []CommonsRunnerImage) {
	o.RunnerImages = v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *CommonsListRunnerImagesOutput) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *CommonsListRunnerImagesOutput) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *CommonsListRunnerImagesOutput) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *CommonsListRunnerImagesOutput) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsListRunnerImagesOutput) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *CommonsListRunnerImagesOutput) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *CommonsListRunnerImagesOutput) SetTotalPages(v int32) {
	o.TotalPages = &v
}

func (o CommonsListRunnerImagesOutput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsListRunnerImagesOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.NextPage) {
		toSerialize["next_page"] = o.NextPage
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	toSerialize["runner_images"] = o.RunnerImages
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsListRunnerImagesOutput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"runner_images",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCommonsListRunnerImagesOutput := _CommonsListRunnerImagesOutput{}

	err = json.Unmarshal(data, &varCommonsListRunnerImagesOutput)

	if err != nil {
		return err
	}

	*o = CommonsListRunnerImagesOutput(varCommonsListRunnerImagesOutput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "next_page")
		delete(additionalProperties, "page")
		delete(additionalProperties, "per_page")
		delete(additionalProperties, "runner_images")
		delete(additionalProperties, "total_items")
		delete(additionalProperties, "total_pages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsListRunnerImagesOutput struct {
	value *CommonsListRunnerImagesOutput
	isSet bool
}

func (v NullableCommonsListRunnerImagesOutput) Get() *CommonsListRunnerImagesOutput {
	return v.value
}

func (v *NullableCommonsListRunnerImagesOutput) Set(val *CommonsListRunnerImagesOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsListRunnerImagesOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsListRunnerImagesOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsListRunnerImagesOutput(val *CommonsListRunnerImagesOutput) *NullableCommonsListRunnerImagesOutput {
	return &NullableCommonsListRunnerImagesOutput{value: val, isSet: true}
}

func (v NullableCommonsListRunnerImagesOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsListRunnerImagesOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
