/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsEC2Configurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsEC2Configurations{}

// CommonsEC2Configurations struct for CommonsEC2Configurations
type CommonsEC2Configurations struct {
	CacheBucket                *string                `json:"cache_bucket,omitempty"`
	DockerBuilderSecurityGroup *string                `json:"docker_builder_security_group,omitempty"`
	ObservabilityBucket        *string                `json:"observability_bucket,omitempty"`
	RoleArn                    *string                `json:"role_arn,omitempty"`
	SecurityGroup              []string               `json:"security_group,omitempty"`
	Subnets                    []SubnetInput          `json:"subnets,omitempty"`
	TmplParams                 map[string]interface{} `json:"tmpl_params,omitempty"`
	VpcId                      *string                `json:"vpc_id,omitempty"`
	AdditionalProperties       map[string]interface{}
}

type _CommonsEC2Configurations CommonsEC2Configurations

// NewCommonsEC2Configurations instantiates a new CommonsEC2Configurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsEC2Configurations() *CommonsEC2Configurations {
	this := CommonsEC2Configurations{}
	return &this
}

// NewCommonsEC2ConfigurationsWithDefaults instantiates a new CommonsEC2Configurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsEC2ConfigurationsWithDefaults() *CommonsEC2Configurations {
	this := CommonsEC2Configurations{}
	return &this
}

// GetCacheBucket returns the CacheBucket field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetCacheBucket() string {
	if o == nil || IsNil(o.CacheBucket) {
		var ret string
		return ret
	}
	return *o.CacheBucket
}

// GetCacheBucketOk returns a tuple with the CacheBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetCacheBucketOk() (*string, bool) {
	if o == nil || IsNil(o.CacheBucket) {
		return nil, false
	}
	return o.CacheBucket, true
}

// HasCacheBucket returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasCacheBucket() bool {
	if o != nil && !IsNil(o.CacheBucket) {
		return true
	}

	return false
}

// SetCacheBucket gets a reference to the given string and assigns it to the CacheBucket field.
func (o *CommonsEC2Configurations) SetCacheBucket(v string) {
	o.CacheBucket = &v
}

// GetDockerBuilderSecurityGroup returns the DockerBuilderSecurityGroup field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetDockerBuilderSecurityGroup() string {
	if o == nil || IsNil(o.DockerBuilderSecurityGroup) {
		var ret string
		return ret
	}
	return *o.DockerBuilderSecurityGroup
}

// GetDockerBuilderSecurityGroupOk returns a tuple with the DockerBuilderSecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetDockerBuilderSecurityGroupOk() (*string, bool) {
	if o == nil || IsNil(o.DockerBuilderSecurityGroup) {
		return nil, false
	}
	return o.DockerBuilderSecurityGroup, true
}

// HasDockerBuilderSecurityGroup returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasDockerBuilderSecurityGroup() bool {
	if o != nil && !IsNil(o.DockerBuilderSecurityGroup) {
		return true
	}

	return false
}

// SetDockerBuilderSecurityGroup gets a reference to the given string and assigns it to the DockerBuilderSecurityGroup field.
func (o *CommonsEC2Configurations) SetDockerBuilderSecurityGroup(v string) {
	o.DockerBuilderSecurityGroup = &v
}

// GetObservabilityBucket returns the ObservabilityBucket field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetObservabilityBucket() string {
	if o == nil || IsNil(o.ObservabilityBucket) {
		var ret string
		return ret
	}
	return *o.ObservabilityBucket
}

// GetObservabilityBucketOk returns a tuple with the ObservabilityBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetObservabilityBucketOk() (*string, bool) {
	if o == nil || IsNil(o.ObservabilityBucket) {
		return nil, false
	}
	return o.ObservabilityBucket, true
}

// HasObservabilityBucket returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasObservabilityBucket() bool {
	if o != nil && !IsNil(o.ObservabilityBucket) {
		return true
	}

	return false
}

// SetObservabilityBucket gets a reference to the given string and assigns it to the ObservabilityBucket field.
func (o *CommonsEC2Configurations) SetObservabilityBucket(v string) {
	o.ObservabilityBucket = &v
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn) {
		var ret string
		return ret
	}
	return *o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetRoleArnOk() (*string, bool) {
	if o == nil || IsNil(o.RoleArn) {
		return nil, false
	}
	return o.RoleArn, true
}

// HasRoleArn returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasRoleArn() bool {
	if o != nil && !IsNil(o.RoleArn) {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given string and assigns it to the RoleArn field.
func (o *CommonsEC2Configurations) SetRoleArn(v string) {
	o.RoleArn = &v
}

// GetSecurityGroup returns the SecurityGroup field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetSecurityGroup() []string {
	if o == nil || IsNil(o.SecurityGroup) {
		var ret []string
		return ret
	}
	return o.SecurityGroup
}

// GetSecurityGroupOk returns a tuple with the SecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetSecurityGroupOk() ([]string, bool) {
	if o == nil || IsNil(o.SecurityGroup) {
		return nil, false
	}
	return o.SecurityGroup, true
}

// HasSecurityGroup returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasSecurityGroup() bool {
	if o != nil && !IsNil(o.SecurityGroup) {
		return true
	}

	return false
}

// SetSecurityGroup gets a reference to the given []string and assigns it to the SecurityGroup field.
func (o *CommonsEC2Configurations) SetSecurityGroup(v []string) {
	o.SecurityGroup = v
}

// GetSubnets returns the Subnets field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetSubnets() []SubnetInput {
	if o == nil || IsNil(o.Subnets) {
		var ret []SubnetInput
		return ret
	}
	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetSubnetsOk() ([]SubnetInput, bool) {
	if o == nil || IsNil(o.Subnets) {
		return nil, false
	}
	return o.Subnets, true
}

// HasSubnets returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasSubnets() bool {
	if o != nil && !IsNil(o.Subnets) {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given []SubnetInput and assigns it to the Subnets field.
func (o *CommonsEC2Configurations) SetSubnets(v []SubnetInput) {
	o.Subnets = v
}

// GetTmplParams returns the TmplParams field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetTmplParams() map[string]interface{} {
	if o == nil || IsNil(o.TmplParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.TmplParams
}

// GetTmplParamsOk returns a tuple with the TmplParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetTmplParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TmplParams) {
		return map[string]interface{}{}, false
	}
	return o.TmplParams, true
}

// HasTmplParams returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasTmplParams() bool {
	if o != nil && !IsNil(o.TmplParams) {
		return true
	}

	return false
}

// SetTmplParams gets a reference to the given map[string]interface{} and assigns it to the TmplParams field.
func (o *CommonsEC2Configurations) SetTmplParams(v map[string]interface{}) {
	o.TmplParams = v
}

// GetVpcId returns the VpcId field value if set, zero value otherwise.
func (o *CommonsEC2Configurations) GetVpcId() string {
	if o == nil || IsNil(o.VpcId) {
		var ret string
		return ret
	}
	return *o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsEC2Configurations) GetVpcIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcId) {
		return nil, false
	}
	return o.VpcId, true
}

// HasVpcId returns a boolean if a field has been set.
func (o *CommonsEC2Configurations) HasVpcId() bool {
	if o != nil && !IsNil(o.VpcId) {
		return true
	}

	return false
}

// SetVpcId gets a reference to the given string and assigns it to the VpcId field.
func (o *CommonsEC2Configurations) SetVpcId(v string) {
	o.VpcId = &v
}

func (o CommonsEC2Configurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsEC2Configurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CacheBucket) {
		toSerialize["cache_bucket"] = o.CacheBucket
	}
	if !IsNil(o.DockerBuilderSecurityGroup) {
		toSerialize["docker_builder_security_group"] = o.DockerBuilderSecurityGroup
	}
	if !IsNil(o.ObservabilityBucket) {
		toSerialize["observability_bucket"] = o.ObservabilityBucket
	}
	if !IsNil(o.RoleArn) {
		toSerialize["role_arn"] = o.RoleArn
	}
	if !IsNil(o.SecurityGroup) {
		toSerialize["security_group"] = o.SecurityGroup
	}
	if !IsNil(o.Subnets) {
		toSerialize["subnets"] = o.Subnets
	}
	if !IsNil(o.TmplParams) {
		toSerialize["tmpl_params"] = o.TmplParams
	}
	if !IsNil(o.VpcId) {
		toSerialize["vpc_id"] = o.VpcId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsEC2Configurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsEC2Configurations := _CommonsEC2Configurations{}

	err = json.Unmarshal(data, &varCommonsEC2Configurations)

	if err != nil {
		return err
	}

	*o = CommonsEC2Configurations(varCommonsEC2Configurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cache_bucket")
		delete(additionalProperties, "docker_builder_security_group")
		delete(additionalProperties, "observability_bucket")
		delete(additionalProperties, "role_arn")
		delete(additionalProperties, "security_group")
		delete(additionalProperties, "subnets")
		delete(additionalProperties, "tmpl_params")
		delete(additionalProperties, "vpc_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsEC2Configurations struct {
	value *CommonsEC2Configurations
	isSet bool
}

func (v NullableCommonsEC2Configurations) Get() *CommonsEC2Configurations {
	return v.value
}

func (v *NullableCommonsEC2Configurations) Set(val *CommonsEC2Configurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsEC2Configurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsEC2Configurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsEC2Configurations(val *CommonsEC2Configurations) *NullableCommonsEC2Configurations {
	return &NullableCommonsEC2Configurations{value: val, isSet: true}
}

func (v NullableCommonsEC2Configurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsEC2Configurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
