/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SubnetInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetInput{}

// SubnetInput struct for SubnetInput
type SubnetInput struct {
	Az                   string `json:"az"`
	Id                   string `json:"id"`
	IsPublic             bool   `json:"is_public"`
	AdditionalProperties map[string]interface{}
}

type _SubnetInput SubnetInput

// NewSubnetInput instantiates a new SubnetInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetInput(az string, id string, isPublic bool) *SubnetInput {
	this := SubnetInput{}
	this.Az = az
	this.Id = id
	this.IsPublic = isPublic
	return &this
}

// NewSubnetInputWithDefaults instantiates a new SubnetInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetInputWithDefaults() *SubnetInput {
	this := SubnetInput{}
	return &this
}

// GetAz returns the Az field value
func (o *SubnetInput) GetAz() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Az
}

// GetAzOk returns a tuple with the Az field value
// and a boolean to check if the value has been set.
func (o *SubnetInput) GetAzOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Az, true
}

// SetAz sets field value
func (o *SubnetInput) SetAz(v string) {
	o.Az = v
}

// GetId returns the Id field value
func (o *SubnetInput) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *SubnetInput) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *SubnetInput) SetId(v string) {
	o.Id = v
}

// GetIsPublic returns the IsPublic field value
func (o *SubnetInput) GetIsPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value
// and a boolean to check if the value has been set.
func (o *SubnetInput) GetIsPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsPublic, true
}

// SetIsPublic sets field value
func (o *SubnetInput) SetIsPublic(v bool) {
	o.IsPublic = v
}

func (o SubnetInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["az"] = o.Az
	toSerialize["id"] = o.Id
	toSerialize["is_public"] = o.IsPublic

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SubnetInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"az",
		"id",
		"is_public",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnetInput := _SubnetInput{}

	err = json.Unmarshal(data, &varSubnetInput)

	if err != nil {
		return err
	}

	*o = SubnetInput(varSubnetInput)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "az")
		delete(additionalProperties, "id")
		delete(additionalProperties, "is_public")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSubnetInput struct {
	value *SubnetInput
	isSet bool
}

func (v NullableSubnetInput) Get() *SubnetInput {
	return v.value
}

func (v *NullableSubnetInput) Set(val *SubnetInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetInput(val *SubnetInput) *NullableSubnetInput {
	return &NullableSubnetInput{value: val, isSet: true}
}

func (v NullableSubnetInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
