/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsRunnerImageVersionMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsRunnerImageVersionMeta{}

// CommonsRunnerImageVersionMeta struct for CommonsRunnerImageVersionMeta
type CommonsRunnerImageVersionMeta struct {
	Event                map[string]interface{} `json:"event,omitempty"`
	ParsedEvent          map[string]interface{} `json:"parsed_event,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsRunnerImageVersionMeta CommonsRunnerImageVersionMeta

// NewCommonsRunnerImageVersionMeta instantiates a new CommonsRunnerImageVersionMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsRunnerImageVersionMeta() *CommonsRunnerImageVersionMeta {
	this := CommonsRunnerImageVersionMeta{}
	return &this
}

// NewCommonsRunnerImageVersionMetaWithDefaults instantiates a new CommonsRunnerImageVersionMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsRunnerImageVersionMetaWithDefaults() *CommonsRunnerImageVersionMeta {
	this := CommonsRunnerImageVersionMeta{}
	return &this
}

// GetEvent returns the Event field value if set, zero value otherwise.
func (o *CommonsRunnerImageVersionMeta) GetEvent() map[string]interface{} {
	if o == nil || IsNil(o.Event) {
		var ret map[string]interface{}
		return ret
	}
	return o.Event
}

// GetEventOk returns a tuple with the Event field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerImageVersionMeta) GetEventOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Event) {
		return map[string]interface{}{}, false
	}
	return o.Event, true
}

// HasEvent returns a boolean if a field has been set.
func (o *CommonsRunnerImageVersionMeta) HasEvent() bool {
	if o != nil && !IsNil(o.Event) {
		return true
	}

	return false
}

// SetEvent gets a reference to the given map[string]interface{} and assigns it to the Event field.
func (o *CommonsRunnerImageVersionMeta) SetEvent(v map[string]interface{}) {
	o.Event = v
}

// GetParsedEvent returns the ParsedEvent field value if set, zero value otherwise.
func (o *CommonsRunnerImageVersionMeta) GetParsedEvent() map[string]interface{} {
	if o == nil || IsNil(o.ParsedEvent) {
		var ret map[string]interface{}
		return ret
	}
	return o.ParsedEvent
}

// GetParsedEventOk returns a tuple with the ParsedEvent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerImageVersionMeta) GetParsedEventOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.ParsedEvent) {
		return map[string]interface{}{}, false
	}
	return o.ParsedEvent, true
}

// HasParsedEvent returns a boolean if a field has been set.
func (o *CommonsRunnerImageVersionMeta) HasParsedEvent() bool {
	if o != nil && !IsNil(o.ParsedEvent) {
		return true
	}

	return false
}

// SetParsedEvent gets a reference to the given map[string]interface{} and assigns it to the ParsedEvent field.
func (o *CommonsRunnerImageVersionMeta) SetParsedEvent(v map[string]interface{}) {
	o.ParsedEvent = v
}

func (o CommonsRunnerImageVersionMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsRunnerImageVersionMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Event) {
		toSerialize["event"] = o.Event
	}
	if !IsNil(o.ParsedEvent) {
		toSerialize["parsed_event"] = o.ParsedEvent
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsRunnerImageVersionMeta) UnmarshalJSON(data []byte) (err error) {
	varCommonsRunnerImageVersionMeta := _CommonsRunnerImageVersionMeta{}

	err = json.Unmarshal(data, &varCommonsRunnerImageVersionMeta)

	if err != nil {
		return err
	}

	*o = CommonsRunnerImageVersionMeta(varCommonsRunnerImageVersionMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "event")
		delete(additionalProperties, "parsed_event")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsRunnerImageVersionMeta struct {
	value *CommonsRunnerImageVersionMeta
	isSet bool
}

func (v NullableCommonsRunnerImageVersionMeta) Get() *CommonsRunnerImageVersionMeta {
	return v.value
}

func (v *NullableCommonsRunnerImageVersionMeta) Set(val *CommonsRunnerImageVersionMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsRunnerImageVersionMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsRunnerImageVersionMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsRunnerImageVersionMeta(val *CommonsRunnerImageVersionMeta) *NullableCommonsRunnerImageVersionMeta {
	return &NullableCommonsRunnerImageVersionMeta{value: val, isSet: true}
}

func (v NullableCommonsRunnerImageVersionMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsRunnerImageVersionMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
