/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsRunnerPool type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsRunnerPool{}

// CommonsRunnerPool struct for CommonsRunnerPool
type CommonsRunnerPool struct {
	CreatedAt            *string `json:"created_at,omitempty"`
	Id                   *string `json:"id,omitempty"`
	Provider             *string `json:"provider,omitempty"`
	RunnerSetId          *string `json:"runner_set_id,omitempty"`
	Size                 *int32  `json:"size,omitempty"`
	UpdatedAt            *string `json:"updated_at,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsRunnerPool CommonsRunnerPool

// NewCommonsRunnerPool instantiates a new CommonsRunnerPool object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsRunnerPool() *CommonsRunnerPool {
	this := CommonsRunnerPool{}
	return &this
}

// NewCommonsRunnerPoolWithDefaults instantiates a new CommonsRunnerPool object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsRunnerPoolWithDefaults() *CommonsRunnerPool {
	this := CommonsRunnerPool{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CommonsRunnerPool) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CommonsRunnerPool) SetId(v string) {
	o.Id = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetProvider() string {
	if o == nil || IsNil(o.Provider) {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetProviderOk() (*string, bool) {
	if o == nil || IsNil(o.Provider) {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasProvider() bool {
	if o != nil && !IsNil(o.Provider) {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *CommonsRunnerPool) SetProvider(v string) {
	o.Provider = &v
}

// GetRunnerSetId returns the RunnerSetId field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetRunnerSetId() string {
	if o == nil || IsNil(o.RunnerSetId) {
		var ret string
		return ret
	}
	return *o.RunnerSetId
}

// GetRunnerSetIdOk returns a tuple with the RunnerSetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetRunnerSetIdOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerSetId) {
		return nil, false
	}
	return o.RunnerSetId, true
}

// HasRunnerSetId returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasRunnerSetId() bool {
	if o != nil && !IsNil(o.RunnerSetId) {
		return true
	}

	return false
}

// SetRunnerSetId gets a reference to the given string and assigns it to the RunnerSetId field.
func (o *CommonsRunnerPool) SetRunnerSetId(v string) {
	o.RunnerSetId = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetSize() int32 {
	if o == nil || IsNil(o.Size) {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *CommonsRunnerPool) SetSize(v int32) {
	o.Size = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CommonsRunnerPool) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsRunnerPool) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CommonsRunnerPool) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *CommonsRunnerPool) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

func (o CommonsRunnerPool) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsRunnerPool) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Provider) {
		toSerialize["provider"] = o.Provider
	}
	if !IsNil(o.RunnerSetId) {
		toSerialize["runner_set_id"] = o.RunnerSetId
	}
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsRunnerPool) UnmarshalJSON(data []byte) (err error) {
	varCommonsRunnerPool := _CommonsRunnerPool{}

	err = json.Unmarshal(data, &varCommonsRunnerPool)

	if err != nil {
		return err
	}

	*o = CommonsRunnerPool(varCommonsRunnerPool)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "id")
		delete(additionalProperties, "provider")
		delete(additionalProperties, "runner_set_id")
		delete(additionalProperties, "size")
		delete(additionalProperties, "updated_at")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsRunnerPool struct {
	value *CommonsRunnerPool
	isSet bool
}

func (v NullableCommonsRunnerPool) Get() *CommonsRunnerPool {
	return v.value
}

func (v *NullableCommonsRunnerPool) Set(val *CommonsRunnerPool) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsRunnerPool) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsRunnerPool) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsRunnerPool(val *CommonsRunnerPool) *NullableCommonsRunnerPool {
	return &NullableCommonsRunnerPool{value: val, isSet: true}
}

func (v NullableCommonsRunnerPool) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsRunnerPool) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
