/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsNomadConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsNomadConfigurations{}

// CommonsNomadConfigurations struct for CommonsNomadConfigurations
type CommonsNomadConfigurations struct {
	// legacy nomad/ controller only
	DataCenter *string `json:"data_center,omitempty"`
	// Used by the nomad-mtls controller (StackNomad).
	DataCenters          []string           `json:"data_centers,omitempty"`
	Host                 *string            `json:"host,omitempty"`
	MetaFilters          *map[string]string `json:"meta_filters,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsNomadConfigurations CommonsNomadConfigurations

// NewCommonsNomadConfigurations instantiates a new CommonsNomadConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsNomadConfigurations() *CommonsNomadConfigurations {
	this := CommonsNomadConfigurations{}
	return &this
}

// NewCommonsNomadConfigurationsWithDefaults instantiates a new CommonsNomadConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsNomadConfigurationsWithDefaults() *CommonsNomadConfigurations {
	this := CommonsNomadConfigurations{}
	return &this
}

// GetDataCenter returns the DataCenter field value if set, zero value otherwise.
func (o *CommonsNomadConfigurations) GetDataCenter() string {
	if o == nil || IsNil(o.DataCenter) {
		var ret string
		return ret
	}
	return *o.DataCenter
}

// GetDataCenterOk returns a tuple with the DataCenter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsNomadConfigurations) GetDataCenterOk() (*string, bool) {
	if o == nil || IsNil(o.DataCenter) {
		return nil, false
	}
	return o.DataCenter, true
}

// HasDataCenter returns a boolean if a field has been set.
func (o *CommonsNomadConfigurations) HasDataCenter() bool {
	if o != nil && !IsNil(o.DataCenter) {
		return true
	}

	return false
}

// SetDataCenter gets a reference to the given string and assigns it to the DataCenter field.
func (o *CommonsNomadConfigurations) SetDataCenter(v string) {
	o.DataCenter = &v
}

// GetDataCenters returns the DataCenters field value if set, zero value otherwise.
func (o *CommonsNomadConfigurations) GetDataCenters() []string {
	if o == nil || IsNil(o.DataCenters) {
		var ret []string
		return ret
	}
	return o.DataCenters
}

// GetDataCentersOk returns a tuple with the DataCenters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsNomadConfigurations) GetDataCentersOk() ([]string, bool) {
	if o == nil || IsNil(o.DataCenters) {
		return nil, false
	}
	return o.DataCenters, true
}

// HasDataCenters returns a boolean if a field has been set.
func (o *CommonsNomadConfigurations) HasDataCenters() bool {
	if o != nil && !IsNil(o.DataCenters) {
		return true
	}

	return false
}

// SetDataCenters gets a reference to the given []string and assigns it to the DataCenters field.
func (o *CommonsNomadConfigurations) SetDataCenters(v []string) {
	o.DataCenters = v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *CommonsNomadConfigurations) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsNomadConfigurations) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *CommonsNomadConfigurations) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *CommonsNomadConfigurations) SetHost(v string) {
	o.Host = &v
}

// GetMetaFilters returns the MetaFilters field value if set, zero value otherwise.
func (o *CommonsNomadConfigurations) GetMetaFilters() map[string]string {
	if o == nil || IsNil(o.MetaFilters) {
		var ret map[string]string
		return ret
	}
	return *o.MetaFilters
}

// GetMetaFiltersOk returns a tuple with the MetaFilters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsNomadConfigurations) GetMetaFiltersOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.MetaFilters) {
		return nil, false
	}
	return o.MetaFilters, true
}

// HasMetaFilters returns a boolean if a field has been set.
func (o *CommonsNomadConfigurations) HasMetaFilters() bool {
	if o != nil && !IsNil(o.MetaFilters) {
		return true
	}

	return false
}

// SetMetaFilters gets a reference to the given map[string]string and assigns it to the MetaFilters field.
func (o *CommonsNomadConfigurations) SetMetaFilters(v map[string]string) {
	o.MetaFilters = &v
}

func (o CommonsNomadConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsNomadConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DataCenter) {
		toSerialize["data_center"] = o.DataCenter
	}
	if !IsNil(o.DataCenters) {
		toSerialize["data_centers"] = o.DataCenters
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.MetaFilters) {
		toSerialize["meta_filters"] = o.MetaFilters
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsNomadConfigurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsNomadConfigurations := _CommonsNomadConfigurations{}

	err = json.Unmarshal(data, &varCommonsNomadConfigurations)

	if err != nil {
		return err
	}

	*o = CommonsNomadConfigurations(varCommonsNomadConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data_center")
		delete(additionalProperties, "data_centers")
		delete(additionalProperties, "host")
		delete(additionalProperties, "meta_filters")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsNomadConfigurations struct {
	value *CommonsNomadConfigurations
	isSet bool
}

func (v NullableCommonsNomadConfigurations) Get() *CommonsNomadConfigurations {
	return v.value
}

func (v *NullableCommonsNomadConfigurations) Set(val *CommonsNomadConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsNomadConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsNomadConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsNomadConfigurations(val *CommonsNomadConfigurations) *NullableCommonsNomadConfigurations {
	return &NullableCommonsNomadConfigurations{value: val, isSet: true}
}

func (v NullableCommonsNomadConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsNomadConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
