/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsOrchardConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsOrchardConfigurations{}

// CommonsOrchardConfigurations struct for CommonsOrchardConfigurations
type CommonsOrchardConfigurations struct {
	Host                 *string `json:"host,omitempty"`
	VmPassword           *string `json:"vm_password,omitempty"`
	VmUsername           *string `json:"vm_username,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsOrchardConfigurations CommonsOrchardConfigurations

// NewCommonsOrchardConfigurations instantiates a new CommonsOrchardConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsOrchardConfigurations() *CommonsOrchardConfigurations {
	this := CommonsOrchardConfigurations{}
	return &this
}

// NewCommonsOrchardConfigurationsWithDefaults instantiates a new CommonsOrchardConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsOrchardConfigurationsWithDefaults() *CommonsOrchardConfigurations {
	this := CommonsOrchardConfigurations{}
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *CommonsOrchardConfigurations) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrchardConfigurations) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *CommonsOrchardConfigurations) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *CommonsOrchardConfigurations) SetHost(v string) {
	o.Host = &v
}

// GetVmPassword returns the VmPassword field value if set, zero value otherwise.
func (o *CommonsOrchardConfigurations) GetVmPassword() string {
	if o == nil || IsNil(o.VmPassword) {
		var ret string
		return ret
	}
	return *o.VmPassword
}

// GetVmPasswordOk returns a tuple with the VmPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrchardConfigurations) GetVmPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.VmPassword) {
		return nil, false
	}
	return o.VmPassword, true
}

// HasVmPassword returns a boolean if a field has been set.
func (o *CommonsOrchardConfigurations) HasVmPassword() bool {
	if o != nil && !IsNil(o.VmPassword) {
		return true
	}

	return false
}

// SetVmPassword gets a reference to the given string and assigns it to the VmPassword field.
func (o *CommonsOrchardConfigurations) SetVmPassword(v string) {
	o.VmPassword = &v
}

// GetVmUsername returns the VmUsername field value if set, zero value otherwise.
func (o *CommonsOrchardConfigurations) GetVmUsername() string {
	if o == nil || IsNil(o.VmUsername) {
		var ret string
		return ret
	}
	return *o.VmUsername
}

// GetVmUsernameOk returns a tuple with the VmUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsOrchardConfigurations) GetVmUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.VmUsername) {
		return nil, false
	}
	return o.VmUsername, true
}

// HasVmUsername returns a boolean if a field has been set.
func (o *CommonsOrchardConfigurations) HasVmUsername() bool {
	if o != nil && !IsNil(o.VmUsername) {
		return true
	}

	return false
}

// SetVmUsername gets a reference to the given string and assigns it to the VmUsername field.
func (o *CommonsOrchardConfigurations) SetVmUsername(v string) {
	o.VmUsername = &v
}

func (o CommonsOrchardConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsOrchardConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.VmPassword) {
		toSerialize["vm_password"] = o.VmPassword
	}
	if !IsNil(o.VmUsername) {
		toSerialize["vm_username"] = o.VmUsername
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsOrchardConfigurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsOrchardConfigurations := _CommonsOrchardConfigurations{}

	err = json.Unmarshal(data, &varCommonsOrchardConfigurations)

	if err != nil {
		return err
	}

	*o = CommonsOrchardConfigurations(varCommonsOrchardConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "host")
		delete(additionalProperties, "vm_password")
		delete(additionalProperties, "vm_username")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsOrchardConfigurations struct {
	value *CommonsOrchardConfigurations
	isSet bool
}

func (v NullableCommonsOrchardConfigurations) Get() *CommonsOrchardConfigurations {
	return v.value
}

func (v *NullableCommonsOrchardConfigurations) Set(val *CommonsOrchardConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsOrchardConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsOrchardConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsOrchardConfigurations(val *CommonsOrchardConfigurations) *NullableCommonsOrchardConfigurations {
	return &NullableCommonsOrchardConfigurations{value: val, isSet: true}
}

func (v NullableCommonsOrchardConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsOrchardConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
