/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsGCEConfigurations type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsGCEConfigurations{}

// CommonsGCEConfigurations struct for CommonsGCEConfigurations
type CommonsGCEConfigurations struct {
	CacheBucket         *string `json:"cache_bucket,omitempty"`
	ObservabilityBucket *string `json:"observability_bucket,omitempty"`
	// SecurityGroups is list of firewalls
	SecurityGroup              []string               `json:"security_group,omitempty"`
	StorageServiceAccountEmail *string                `json:"storage_service_account_email,omitempty"`
	Subnets                    []SubnetInput          `json:"subnets,omitempty"`
	TmplParams                 map[string]interface{} `json:"tmpl_params,omitempty"`
	VpcId                      *string                `json:"vpc_id,omitempty"`
	AdditionalProperties       map[string]interface{}
}

type _CommonsGCEConfigurations CommonsGCEConfigurations

// NewCommonsGCEConfigurations instantiates a new CommonsGCEConfigurations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsGCEConfigurations() *CommonsGCEConfigurations {
	this := CommonsGCEConfigurations{}
	return &this
}

// NewCommonsGCEConfigurationsWithDefaults instantiates a new CommonsGCEConfigurations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsGCEConfigurationsWithDefaults() *CommonsGCEConfigurations {
	this := CommonsGCEConfigurations{}
	return &this
}

// GetCacheBucket returns the CacheBucket field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetCacheBucket() string {
	if o == nil || IsNil(o.CacheBucket) {
		var ret string
		return ret
	}
	return *o.CacheBucket
}

// GetCacheBucketOk returns a tuple with the CacheBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetCacheBucketOk() (*string, bool) {
	if o == nil || IsNil(o.CacheBucket) {
		return nil, false
	}
	return o.CacheBucket, true
}

// HasCacheBucket returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasCacheBucket() bool {
	if o != nil && !IsNil(o.CacheBucket) {
		return true
	}

	return false
}

// SetCacheBucket gets a reference to the given string and assigns it to the CacheBucket field.
func (o *CommonsGCEConfigurations) SetCacheBucket(v string) {
	o.CacheBucket = &v
}

// GetObservabilityBucket returns the ObservabilityBucket field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetObservabilityBucket() string {
	if o == nil || IsNil(o.ObservabilityBucket) {
		var ret string
		return ret
	}
	return *o.ObservabilityBucket
}

// GetObservabilityBucketOk returns a tuple with the ObservabilityBucket field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetObservabilityBucketOk() (*string, bool) {
	if o == nil || IsNil(o.ObservabilityBucket) {
		return nil, false
	}
	return o.ObservabilityBucket, true
}

// HasObservabilityBucket returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasObservabilityBucket() bool {
	if o != nil && !IsNil(o.ObservabilityBucket) {
		return true
	}

	return false
}

// SetObservabilityBucket gets a reference to the given string and assigns it to the ObservabilityBucket field.
func (o *CommonsGCEConfigurations) SetObservabilityBucket(v string) {
	o.ObservabilityBucket = &v
}

// GetSecurityGroup returns the SecurityGroup field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetSecurityGroup() []string {
	if o == nil || IsNil(o.SecurityGroup) {
		var ret []string
		return ret
	}
	return o.SecurityGroup
}

// GetSecurityGroupOk returns a tuple with the SecurityGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetSecurityGroupOk() ([]string, bool) {
	if o == nil || IsNil(o.SecurityGroup) {
		return nil, false
	}
	return o.SecurityGroup, true
}

// HasSecurityGroup returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasSecurityGroup() bool {
	if o != nil && !IsNil(o.SecurityGroup) {
		return true
	}

	return false
}

// SetSecurityGroup gets a reference to the given []string and assigns it to the SecurityGroup field.
func (o *CommonsGCEConfigurations) SetSecurityGroup(v []string) {
	o.SecurityGroup = v
}

// GetStorageServiceAccountEmail returns the StorageServiceAccountEmail field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetStorageServiceAccountEmail() string {
	if o == nil || IsNil(o.StorageServiceAccountEmail) {
		var ret string
		return ret
	}
	return *o.StorageServiceAccountEmail
}

// GetStorageServiceAccountEmailOk returns a tuple with the StorageServiceAccountEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetStorageServiceAccountEmailOk() (*string, bool) {
	if o == nil || IsNil(o.StorageServiceAccountEmail) {
		return nil, false
	}
	return o.StorageServiceAccountEmail, true
}

// HasStorageServiceAccountEmail returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasStorageServiceAccountEmail() bool {
	if o != nil && !IsNil(o.StorageServiceAccountEmail) {
		return true
	}

	return false
}

// SetStorageServiceAccountEmail gets a reference to the given string and assigns it to the StorageServiceAccountEmail field.
func (o *CommonsGCEConfigurations) SetStorageServiceAccountEmail(v string) {
	o.StorageServiceAccountEmail = &v
}

// GetSubnets returns the Subnets field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetSubnets() []SubnetInput {
	if o == nil || IsNil(o.Subnets) {
		var ret []SubnetInput
		return ret
	}
	return o.Subnets
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetSubnetsOk() ([]SubnetInput, bool) {
	if o == nil || IsNil(o.Subnets) {
		return nil, false
	}
	return o.Subnets, true
}

// HasSubnets returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasSubnets() bool {
	if o != nil && !IsNil(o.Subnets) {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given []SubnetInput and assigns it to the Subnets field.
func (o *CommonsGCEConfigurations) SetSubnets(v []SubnetInput) {
	o.Subnets = v
}

// GetTmplParams returns the TmplParams field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetTmplParams() map[string]interface{} {
	if o == nil || IsNil(o.TmplParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.TmplParams
}

// GetTmplParamsOk returns a tuple with the TmplParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetTmplParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TmplParams) {
		return map[string]interface{}{}, false
	}
	return o.TmplParams, true
}

// HasTmplParams returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasTmplParams() bool {
	if o != nil && !IsNil(o.TmplParams) {
		return true
	}

	return false
}

// SetTmplParams gets a reference to the given map[string]interface{} and assigns it to the TmplParams field.
func (o *CommonsGCEConfigurations) SetTmplParams(v map[string]interface{}) {
	o.TmplParams = v
}

// GetVpcId returns the VpcId field value if set, zero value otherwise.
func (o *CommonsGCEConfigurations) GetVpcId() string {
	if o == nil || IsNil(o.VpcId) {
		var ret string
		return ret
	}
	return *o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsGCEConfigurations) GetVpcIdOk() (*string, bool) {
	if o == nil || IsNil(o.VpcId) {
		return nil, false
	}
	return o.VpcId, true
}

// HasVpcId returns a boolean if a field has been set.
func (o *CommonsGCEConfigurations) HasVpcId() bool {
	if o != nil && !IsNil(o.VpcId) {
		return true
	}

	return false
}

// SetVpcId gets a reference to the given string and assigns it to the VpcId field.
func (o *CommonsGCEConfigurations) SetVpcId(v string) {
	o.VpcId = &v
}

func (o CommonsGCEConfigurations) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsGCEConfigurations) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CacheBucket) {
		toSerialize["cache_bucket"] = o.CacheBucket
	}
	if !IsNil(o.ObservabilityBucket) {
		toSerialize["observability_bucket"] = o.ObservabilityBucket
	}
	if !IsNil(o.SecurityGroup) {
		toSerialize["security_group"] = o.SecurityGroup
	}
	if !IsNil(o.StorageServiceAccountEmail) {
		toSerialize["storage_service_account_email"] = o.StorageServiceAccountEmail
	}
	if !IsNil(o.Subnets) {
		toSerialize["subnets"] = o.Subnets
	}
	if !IsNil(o.TmplParams) {
		toSerialize["tmpl_params"] = o.TmplParams
	}
	if !IsNil(o.VpcId) {
		toSerialize["vpc_id"] = o.VpcId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsGCEConfigurations) UnmarshalJSON(data []byte) (err error) {
	varCommonsGCEConfigurations := _CommonsGCEConfigurations{}

	err = json.Unmarshal(data, &varCommonsGCEConfigurations)

	if err != nil {
		return err
	}

	*o = CommonsGCEConfigurations(varCommonsGCEConfigurations)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "cache_bucket")
		delete(additionalProperties, "observability_bucket")
		delete(additionalProperties, "security_group")
		delete(additionalProperties, "storage_service_account_email")
		delete(additionalProperties, "subnets")
		delete(additionalProperties, "tmpl_params")
		delete(additionalProperties, "vpc_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsGCEConfigurations struct {
	value *CommonsGCEConfigurations
	isSet bool
}

func (v NullableCommonsGCEConfigurations) Get() *CommonsGCEConfigurations {
	return v.value
}

func (v *NullableCommonsGCEConfigurations) Set(val *CommonsGCEConfigurations) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsGCEConfigurations) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsGCEConfigurations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsGCEConfigurations(val *CommonsGCEConfigurations) *NullableCommonsGCEConfigurations {
	return &NullableCommonsGCEConfigurations{value: val, isSet: true}
}

func (v NullableCommonsGCEConfigurations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsGCEConfigurations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
