/*
Warp Builds API Docs

This is the docs for warp builds api for argonaut

API version: 0.4.0
Contact: support@swagger.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package wbclient

import (
	"encoding/json"
)

// checks if the CommonsKindMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CommonsKindMeta{}

// CommonsKindMeta struct for CommonsKindMeta
type CommonsKindMeta struct {
	Ec2Configurations *CommonsEC2Meta `json:"ec2_configurations,omitempty"`
	// Deprecated: IsPreferred is no longer consulted by the routing binders — preference is encoded in the routing tree's entry order. The (kind, region) invariant requires exactly one active stack, so there's nothing to break ties on. Field stays for compatibility with stored rows; will be removed once data is audited and the column is dropped.
	IsPreferred          *bool `json:"is_preferred,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CommonsKindMeta CommonsKindMeta

// NewCommonsKindMeta instantiates a new CommonsKindMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCommonsKindMeta() *CommonsKindMeta {
	this := CommonsKindMeta{}
	return &this
}

// NewCommonsKindMetaWithDefaults instantiates a new CommonsKindMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCommonsKindMetaWithDefaults() *CommonsKindMeta {
	this := CommonsKindMeta{}
	return &this
}

// GetEc2Configurations returns the Ec2Configurations field value if set, zero value otherwise.
func (o *CommonsKindMeta) GetEc2Configurations() CommonsEC2Meta {
	if o == nil || IsNil(o.Ec2Configurations) {
		var ret CommonsEC2Meta
		return ret
	}
	return *o.Ec2Configurations
}

// GetEc2ConfigurationsOk returns a tuple with the Ec2Configurations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsKindMeta) GetEc2ConfigurationsOk() (*CommonsEC2Meta, bool) {
	if o == nil || IsNil(o.Ec2Configurations) {
		return nil, false
	}
	return o.Ec2Configurations, true
}

// HasEc2Configurations returns a boolean if a field has been set.
func (o *CommonsKindMeta) HasEc2Configurations() bool {
	if o != nil && !IsNil(o.Ec2Configurations) {
		return true
	}

	return false
}

// SetEc2Configurations gets a reference to the given CommonsEC2Meta and assigns it to the Ec2Configurations field.
func (o *CommonsKindMeta) SetEc2Configurations(v CommonsEC2Meta) {
	o.Ec2Configurations = &v
}

// GetIsPreferred returns the IsPreferred field value if set, zero value otherwise.
func (o *CommonsKindMeta) GetIsPreferred() bool {
	if o == nil || IsNil(o.IsPreferred) {
		var ret bool
		return ret
	}
	return *o.IsPreferred
}

// GetIsPreferredOk returns a tuple with the IsPreferred field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CommonsKindMeta) GetIsPreferredOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPreferred) {
		return nil, false
	}
	return o.IsPreferred, true
}

// HasIsPreferred returns a boolean if a field has been set.
func (o *CommonsKindMeta) HasIsPreferred() bool {
	if o != nil && !IsNil(o.IsPreferred) {
		return true
	}

	return false
}

// SetIsPreferred gets a reference to the given bool and assigns it to the IsPreferred field.
func (o *CommonsKindMeta) SetIsPreferred(v bool) {
	o.IsPreferred = &v
}

func (o CommonsKindMeta) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CommonsKindMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ec2Configurations) {
		toSerialize["ec2_configurations"] = o.Ec2Configurations
	}
	if !IsNil(o.IsPreferred) {
		toSerialize["is_preferred"] = o.IsPreferred
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CommonsKindMeta) UnmarshalJSON(data []byte) (err error) {
	varCommonsKindMeta := _CommonsKindMeta{}

	err = json.Unmarshal(data, &varCommonsKindMeta)

	if err != nil {
		return err
	}

	*o = CommonsKindMeta(varCommonsKindMeta)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "ec2_configurations")
		delete(additionalProperties, "is_preferred")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCommonsKindMeta struct {
	value *CommonsKindMeta
	isSet bool
}

func (v NullableCommonsKindMeta) Get() *CommonsKindMeta {
	return v.value
}

func (v *NullableCommonsKindMeta) Set(val *CommonsKindMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableCommonsKindMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableCommonsKindMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCommonsKindMeta(val *CommonsKindMeta) *NullableCommonsKindMeta {
	return &NullableCommonsKindMeta{value: val, isSet: true}
}

func (v NullableCommonsKindMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCommonsKindMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
